### ISSUE TITLE
Usage of FileLikeQueue() and StreamingFile() not documented

### ISSUE THREAD

**Issue by mhcastro** [mar10/wsgidav#104]
The **stream_tools.py** have very brief description of the usage of the `FileLikeQueue()` class, and no description of the `StreamingFile()` class.

How these classes are invoked from WSGIDav? How to invoke them? Is it required to configure WSGIDav to call these classes - if yes, how? Any code change in the dav_provider.py or in any other file?

Thanks in advance.

**Comment by mar10** [comment]
See #48 for some details and motivation.
