### ISSUE TITLE
nginx and wsgidav

### ISSUE THREAD

**Issue by MrMoronIV** [mar10/wsgidav#105]
I already have nginx running on my server, is it possible to put wsgidav behind nginx?

And if so, how would I need to set it up.
With what command do I start wsgi and what do I need to pay attention to in nginx to make it work?

I can setup tls and authentication in nginx and proxy_pass to wsgi. Can I forward to a socket or any special address? Are there instructions somewhere?

Also, is it recommended to do this or is using cheroot better from a technical point of view?

**Comment by mar10** [comment]
WsgiDAV always requires a WSGI compliant server to run in, e.g. cheroot, unicorn, .... 
nginx or Apache may be configured as reverse proxy in front of that.

I haven't set up  authentication with nginx so far. (You can configure `trusted_auth_header` if that helps)
Let us know if you have a running configuration, so we can add it to the docs. Also if you have a concrete feature request that would help to make it work.

[some comparison][1]

[1]: https://blog.appdynamics.com/engineering/a-performance-analysis-of-python-wsgi-servers-part-2/

**Comment by MrMoronIV** [comment]
I kind of ditched the idea to use nginx since I have things setup now perfectly fine with the required web server anyway, It's running on port 444 so no need to add more overhead to it imo by putting another web server in front of it. I was hoping to save system resources by using nginx but that's not possible.
