### ISSUE TITLE
trusted_auth_header - issues getting it to work

### ISSUE THREAD

**Issue by teedog** [mar10/wsgidav#109]
Hi,

I'm trying to get the trusted_auth_header to work but the setup is failing. I'm running wsgidav behind an nginx that exposes the authenticated LDAP user as follows:

    [...]
    server {
            # SSL configuration
            server_name webdav.sld.tld;
    
            listen 443 ssl http2;
            listen [::]:443 ssl http2;
    
            include snippets/ssl-our.dyndns.ws.conf;
            include snippets/ssl-params.conf;
    
            root /var/www/html;
    
            # Add index.php to the list if you are using PHP
            index index.html index.htm index.nginx-debian.html;
    
            set $upstream 10.0.3.56:1080;
    
            dav_methods     PUT DELETE MKCOL COPY MOVE;
            dav_ext_methods   PROPFIND OPTIONS;
            create_full_put_path  on;
            dav_access    user:rw group:rw all:rw;
            autoindex     on;
    
            location / {
              ## Require LDAP authentication
              auth_request /auth-proxy;
    
              proxy_pass     http://$upstream;
              proxy_redirect http://$upstream https://$server_name;
    
              proxy_cache off;
              proxy_store off;
              proxy_buffering off;
              proxy_http_version 1.1;
              proxy_read_timeout 36000s;
    
              proxy_set_header Host $http_host;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-User $remote_user;
              proxy_set_header Referer "";
    
              client_max_body_size 0;
            }
    
            location ~ /\.ht {
                    deny all;
            }
    
    
            location ~ /.well-known {
                    allow all;
            }
    
            # Pull in ldap authentication snippet
            include app.d/default.auth-proxy.conf;
    }
[...]
    
What I tried so far when it comes to wsgidav.conf is the following:

    provider_mapping = {}
    user_mapping = {}
    def addShare(shareName, davProvider):
        provider_mapping[shareName] = davProvider
    def addUser(realmName, user, password, description, roles=[]):
        realmName = "/" + realmName.strip(r"\/")
        userDict = user_mapping.setdefault(realmName, {}).setdefault(user, {})
        userDict["password"] = password
        userDict["description"] = description
        userDict["roles"] = roles
    port = 1080
    host = "0.0.0.0"
    add_header_MS_Author_Via = True
    verbose = 5          # 0 - quiet
                         # 1 - no output (excepting application exceptions)
                         # 2 - warnings and errors only
                         # 3 - show single line request summaries (HTTP logging)
                         # 4 - show additional events
                         # 5 - show full request/response header info (HTTP Logging)
                         #     request body and GET response bodies not shown
    enable_loggers = [ "http_authenticator" ]
    debug_methods = []
    debug_litmus = []
    dir_browser = {
        "enable": True,               # Render HTML listing for GET requests on collections
        "response_trailer": "",       # Raw HTML code, appended as footer
        "davmount": False,            # Send <dm:mount> response if request URL contains '?davmount'
        "ms_mount": False,            # Add an 'open as webfolder' link (requires Windows)
        "ms_sharepoint_plugin": True, # Invoke MS Offce documents for editing using WebDAV
        "ms_sharepoint_urls": False,  # Prepend 'ms-word:ofe|u|' to URL for MS Offce documents
    }
    propsmanager = True
    addShare("", "/volume0/share")
    trusted_auth_header = "X-Forwarded-User"

However when running this config and navigating to "https://webdav.sld.tld" using CyberDuck I'll receive an anonymous listing and the following log file.

    $ wsgidav --version -v
    WsgiDAV/2.4.0 Python/2.7.13 Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
    $ wsgidav --config=/opt/wsgidav/wsgidav.conf
    12:00:20.408 - <140230624671488> wsgidav.wsgidav_app  INFO   :  Default encoding: ascii (file system: UTF-8)
    12:00:20.408 - <140230624671488> wsgidav.wsgidav_app  INFO   :  Middleware stack:
    12:00:20.408 - <140230624671488> wsgidav.wsgidav_app  INFO   :    - <class 'wsgidav.dir_browser.WsgiDavDirBrowser'>
    12:00:20.408 - <140230624671488> wsgidav.wsgidav_app  INFO   :    - <class 'wsgidav.http_authenticator.HTTPAuthenticator'>
    12:00:20.409 - <140230624671488> wsgidav.wsgidav_app  INFO   :    - <class 'wsgidav.error_printer.ErrorPrinter'>
    12:00:20.409 - <140230624671488> wsgidav.wsgidav_app  INFO   :    - <class 'wsgidav.debug_filter.WsgiDavDebugFilter'>
    12:00:20.409 - <140230624671488> wsgidav.wsgidav_app  INFO   :  Using lock manager: LockManager(LockStorageDict)
    12:00:20.409 - <140230624671488> wsgidav.wsgidav_app  INFO   :  Using property manager: PropertyManager
    12:00:20.409 - <140230624671488> wsgidav.wsgidav_app  INFO   :  Using domain controller: WsgiDAVDomainController
    12:00:20.409 - <140230624671488> wsgidav.wsgidav_app  INFO   :  Registered DAV providers:
    12:00:20.410 - <140230624671488> wsgidav.wsgidav_app  INFO   :    Share '/': FilesystemProvider for path '/volume0/share' (Read-Write) (anonymous)
    12:00:20.410 - <140230624671488> wsgidav.wsgidav_app  WARNING:  WARNING: share '/' will allow anonymous access.
    12:00:20.529 - <140230624671488> wsgidav              INFO   :  Running WsgiDAV/2.4.0 Cheroot/6.3.1 Python/2.7.13
    12:00:20.529 - <140230624671488> wsgidav              INFO   :  Serving on http://0.0.0.0:1080 ...
    12:00:31.000 - <140230514829056> wsgidav.http_authenticator DEBUG  :  realm '/'
    12:00:31.000 - <140230514829056> wsgidav.http_authenticator DEBUG  :  No authorization required for realm '/'
    12:00:31.003 - <140230514829056> wsgidav.wsgidav_app  INFO   :  10.0.1.6 - (anonymous) - [2018-06-11 10:00:31] "HEAD /" connection="close", agent="Cyberduck/6.6.1.28146 (Mac OS X/10.13.4) (x86_64)", elap=0.004sec -> 200 OK
    12:00:31.466 - <140230506436352> wsgidav.http_authenticator DEBUG  :  realm '/'
    12:00:31.467 - <140230506436352> wsgidav.http_authenticator DEBUG  :  No authorization required for realm '/'
    12:00:31.473 - <140230506436352> wsgidav.wsgidav_app  INFO   :  10.0.1.6 - (anonymous) - [2018-06-11 10:00:31] "PROPFIND /" length=242, depth=1, connection="close", agent="Cyberduck/6.6.1.28146 (Mac OS X/10.13.4) (x86_64)", elap=0.006sec -> 207 Multi-Status

Please advice where I might have taken a wrong turn.

BRTL

**Comment by teedog** [comment]
I should add to this: Running an `nginx` or `Apache2 HTTPD` WebDAV Server instead of WsgiDAV works. Nginx actually fetches the remote user from the RP. Apache HTTPD requires the use of `mod_ldap_authzn` which takes up the `Authorization` header and performs a second LDAP Auth.

**Comment by mar10** [comment]
This was implemented for #28, #11 
I never used it myself, nor do I have currently a setup to test it.
Maybe you can see more if you increase verbosity (`-vv`)?

**Comment by teedog** [comment]
Hi @mar10, 

thanks - did that and now I'm getting a `ValueError` in `server.py` of `cheroot` and the communication fails completely (CyberDuck reports an error when connecting).

    ValueError("invalid literal for int() with base 10: ''",)
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1193, in communicate
        req.respond()
      File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 997, in respond
        self.server.gateway(self).respond()
      File "/usr/local/lib/python2.7/dist-packages/cheroot/wsgi.py", line 149, in respond
        self.req.ensure_headers_sent()
      File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1044, in ensure_headers_sent
        self.send_headers()
      File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1061, in send_headers
        status = int(self.status[:3])
    ValueError: invalid literal for int() with base 10: ''

I get this behaviour as soon as I start with `-v`. By applying the following modifications to `request_server.py`and `debug_filter.py` I worked around the VE.

    --- debug_filter.py.dist        2018-06-11 22:12:02.867539875 +0200
    +++ debug_filter.py     2018-06-11 22:03:48.735895571 +0200
    @@ -135,7 +135,7 @@
     
             # Dump request headers
             if dumpRequest:
    -            _logger.info("} Request ---".format(method))
    +            _logger.info("{} Request ---".format(method))
                 # _logger.info("<{}> --- {} Request ---".format(
                 #         threading.currentThread().ident, method))
                 for k, v in environ.items():
    
    
    --- request_server.py.dist      2018-06-11 22:11:36.939560843 +0200
    +++ request_server.py   2018-06-11 22:09:31.155659733 +0200
    @@ -49,7 +49,7 @@
             self.allowPropfindInfinite = True
             self._verbose = 2
             self.block_size = DEFAULT_BLOCK_SIZE
    -        _logger.debug("RequestServer: __init__", module="sc")
    +        _logger.debug("RequestServer: __init__")
     
             self._possible_methods = ["OPTIONS", "HEAD", "GET", "PROPFIND"]
             # if self._davProvider.propManager is not None:

Additionally I changed nginx reverse proxy config to *not* forward the `Authorization` header since this could confuse `wsgidav` by adding an additional `proxy_set_header Authorization "";`. Now when performing a login using CyberDuck I'm getting the attached (stripped) logfile.

[wsgidav.log](https://github.com/mar10/wsgidav/files/2091621/wsgidav.log)

BRTL

**Comment by mar10** [comment]
Seems some bugs sneaked in  with the last refactoring. I hope they are fixed with the latest commit, thanks.
The log shows
```
22:17:55.439 - <139927126718208> wsgidav.wsgidav_app  WARNING:  WARNING: share '/' will allow anonymous access.
...
22:18:07.023 - <139927008483072> wsgidav.http_authenticator DEBUG  :  realm '/'
22:18:07.023 - <139927008483072> wsgidav.http_authenticator DEBUG  :  No authorization required for realm '/'
```
What happens if you add an entry for that share in `user_mapping`?

**Comment by teedog** [comment]
Just a short update. I think I found it out myself. Inside the config `trusted_auth_header`has to be set to `HTTP_X_FORWARDED_USER` since that seems to be the right name from the `environment`. After that it's actually okay to remove the `addUser` again - `wsgidav` just accepts the forwarded user name. I'll test everything, wrap this up and close the ticket later on. Thanks for the help @mar10.

**Comment by teedog** [comment]
I was wrong with my previous comment. You need to have the `addUser` for the realm otherwise it will be unprotected (anonymous). However it is irrelevant what user you define there. Every user that is passed from the reverse proxy (using the auth header) is accepted. @mar10, is this the wanted behaviour? I would understand if authorisation is granted when the username that is contained in the auth header matches one of the names defined in the user_mapping. The current behaviour is actually quite different.

**Comment by mar10** [comment]
Thanks for the feedback.

> You need to have the addUser for the realm otherwise it will be unprotected (anonymous). However it is irrelevant what user you define there.
> is this the wanted behaviour? 

This is at least what I expected from looking at the code. This was added by a PR for #28, #11
I never used it myself.

The alternative would mean that you let nginx add the trusted header (by looking up the user from LDAP), but then you have to add every user to the user_map. This could mean to copy and keep in sync a lot of names.
If you have a good spec for a feature that handles this scenario, would you open a new issue for this for discussion? I am closing this one for now.
(A similar request was opened recently btw: #108 )
