### ISSUE TITLE
WsgiDAVApp does not allow upstream authentication

### ISSUE THREAD

**Issue by BrianSipos** [mar10/wsgidav#11]
This is not too big of a deal for me, but I am using WsgiDAVAPP behind Apache HTTP authentication / authorization layer. Currently, there is no way to interrupt the WsgiDAVApp stack to avoid or replace use of HTTPAuthenticator object. This makes it impossible to substitute value for environ['http_authenticator.username'] as HTTPAuthenticator sets it to the empty string if not used.

It would be convenient to have a way to control use of HTTPAuthenticator similar to how the config option "dir_browser" controls use of WsgiDavDirBrowser.

**Comment by mar10** [comment]
I started a branch for this, see #28
