### ISSUE TITLE
Use of open with parameter encoding is not Py2.7 safe

### ISSUE THREAD

**Issue by teedog** [mar10/wsgidav#111]
Inside `server_cli.py` the python built-in `open` is used with parameter `encoding`. While this is fine for Py3 it breaks Py2.7 compatibility.

**Current Behaviour**
* When running wsgidav with Py2.7 it breaks on reading the config file

**Expected Behaviour**
* wsgidav should fully support Py2.7
* IMO the most straightforward way to achieve this would be to use `io.open` instead (see attached patch file)

[server_cli.patch.txt](https://github.com/mar10/wsgidav/files/2097997/server_cli.patch.txt)

**Comment by mar10** [comment]
Thanks!
