### ISSUE TITLE
Signals

### ISSUE THREAD

**Issue by n3storm** [mar10/wsgidav#113]
I am making my own provider and controller (subclassing wsgidav's) to add three features:

- realms and users/groups/profiles from database: currently prototype with tinydb. I want to be able to do CRUD operations in real time. Not sure if possible. I'll keep you updated.
- signals: for creating notifications, auditing, etc.
- rest api: first only for db so in a future a web panel interacting with wsgi to create realms and users/groups/profiles, panel user auth/permission and show notifications, collection history.... A webdav client to operate on files/folders.

This is kind of ambitious, as I am trying to replace Pydio 8 (I don't like the cells/golang movement), let's see where this ends (anybody interested?)

**On signals**: I think signals should be added at wsgidav level so all the project may benefit of this pattern.

I am using signalslot library and looks enough for this https://pypi.org/project/signalslot/

The idea is adding emitters on all filesystem operations. There are several uses for this: collection/file history. Notifications (email, telegram, web) like "User fuu updated /folder1/file2 2 hours ago".

I am also using signals as callbacks to check "write" permissions. This way I can make a Realm/repository readonly for certain user/group/profile. For "customer portals" for example.

Note: I am using miracle acl library to check for access but this can be keep out from wsgidav project and let dev choose.

To end up, thanks Martin for your software and release 3 works like a charm and looks like a great improvement for devs.

**Comment by n3storm** [comment]
Do you want me to propose a pull request or just upload my code to study usage?

Thanks

Note: I added wsgidav reload on change to include new realms created on database. Also at the same time I am serving a flask app for API, in another thread. Using gevent.pywsgi

```
#~ from cheroot import wsgi
import gevent
import gevent.monkey
gevent.monkey.patch_all()
from gevent.pywsgi import WSGIServer
from werkzeug.serving import run_with_reloader

import api
import providers
import controllers
import davapp
import logging

logger = logging.getLogger("wsgidav")
logger.addHandler(logging.FileHandler('hello.log'))
logger.propagate = True
logger.setLevel(logging.DEBUG)

from tinydb import TinyDB

realms = TinyDB("db/realms.json")
#~ realms.insert({'name':'principal','uri':'/','path':'/home/gollum/Proyectos/Limbo/limbo/local'})
#~ realms.insert({'name':'second','uri':'/2','path':'/home/gollum/Proyectos/Limbo/limbo/local2'})

users = TinyDB("db/users.json")
#~ users.insert({'username': 'user1', 'password': 'afsasdf','group':'group1',"roles": ['admin',],'realm':'/'})
#~ users.insert({'username': 'user2', 'password': 'asfasf','group':'group2',"roles": ['admin',],'realm':'/'})
#~ users.insert({'username': 'user3', 'password': 'asdfasdf','group':'group2',"roles": ['admin',],'realm':'/2'})

config = {
    "host": "0.0.0.0",
    "port": 8080,
    "error_printer": {
        "catch_all": True,  # False,
    },
    "verbose": 4,
    "http_authenticator": {
        "accept_basic": False,
        "accept_digest": True,
        "default_to_digest": True,
        },
    "domain_controller": controllers.DomainLimboController(),
    "users_db": users,
    "realms_db": realms,
    }

config['provider_mapping'] = {}
app = davapp.LimboDAVApp(config)

server_args = {
    "bind_addr": (config["host"], config["port"]),
    "wsgi_app": app,
    }

import _thread as thread

def api_thread():
    api_server = WSGIServer((config["host"], config["port"] + 1), api.api)
    api_greenlet = gevent.spawn(api_server.serve_forever())

@run_with_reloader
def serve():
    thread.start_new_thread(api_thread,)
    dav_server = WSGIServer((config["host"], config["port"]), app)
    dav_greenlet = gevent.spawn(dav_server.serve_forever())
    
serve()
```

**Comment by n3storm** [comment]
WSGIDAV BROWSER
![seleccion_057](https://user-images.githubusercontent.com/220748/41835557-56890d9e-7858-11e8-8abf-744a8b9e1614.png)

API
![seleccion_058](https://user-images.githubusercontent.com/220748/41835542-46a17ace-7858-11e8-91a3-48a5d9496b3a.png)

THUNAR gvfs
![seleccion_059](https://user-images.githubusercontent.com/220748/41835608-8a144354-7858-11e8-8cff-8b7158e1b1b3.png)

DJANGO web 
![seleccion_056](https://user-images.githubusercontent.com/220748/41835636-9fcf236c-7858-11e8-8b4f-ce77097c4d1a.png)
client

**Comment by mar10** [comment]
> Do you want me to propose a pull request or just upload my code to study usage?

If you have a fork with a feature branch, we can discuss there. If you want to share your code separately that's fine as well. 
I am not sure if I understand enough what parts of it could be part of WsgiDAV (core, demo apps, docs), and what is unrelated built on top of it.

**Comment by n3storm** [comment]
Sorry I am off for a while. I will try to be back in august with some code.

**Comment by mar10** [comment]
No problem. Please keep in mind that the current way of adding behavior to WsgiDAV is by overriding and deriving.
I generally try to follow *There should be one-- and preferably only one --obvious way to do it.*
I'd like to understand better why another approach (*signals*) is required or beneficial to solve the use case, so I am curious with whatever you come up with ;-)

**Comment by mar10** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that enquired information is missing, it is not reproducible, or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version.
You can also contribute directly by providing a patch.

Thank you!
