### ISSUE TITLE
How do I define NTDomainController for WSGIDAV ?

### ISSUE THREAD

**Issue by olafkfreund** [mar10/wsgidav#115]
Hi
Thanks for a great software. I wonder how I define NTDomainControler i wsgidav.conf ?
Have tried a few things but i do not work. Please include an example. Thank You so much.

**Comment by n3storm** [comment]
which ones did you tried?

Did you read begining of this file?:
https://github.com/mar10/wsgidav/blob/master/wsgidav/addons/nt_domain_controller.py

**Comment by olafkfreund** [comment]
Yeah i did.. thank you for answering.
But this is what I get:    
 import win32net  # @UnresolvedImport
ModuleNotFoundError: No module named 'win32net'

**Comment by n3storm** [comment]
Can you explain what steps you followed to create a python environment or how did you installed python in windows?

**Comment by olafkfreund** [comment]
Hi again
Resolved the win32net issue by installing the win32net module BUT is still get an error when using:

from wsgidav.addons.nt_domain_controller import NTDomainController
domain_controller = NTDomainController(presetdomain=None, presetserver=None)
http_authenticator = {
    "accept_basic": True,
    "accept_digest": False,
    "default_to_digest": False,
    }
ing the wsgidav.yaml config

**Comment by n3storm** [comment]
can you paste error log?

**Comment by olafkfreund** [comment]
Or if I use the wsgidav.conf file 


wsgidav.exe : Traceback (most recent call last):
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "c:\users\ppnadmin.customers\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ppnadmin.customers\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ppnadmin.CUSTOMERS\AppData\Local\Programs\Python\Python36\Scripts\wsgidav.exe\__main__.py", line 9, in <module>
  File "c:\users\ppnadmin.customers\appdata\local\programs\python\python36\lib\site-packages\wsgidav\server\server_cli.py", line 583, in run
    app = WsgiDAVApp(config)
  File "c:\users\ppnadmin.customers\appdata\local\programs\python\python36\lib\site-packages\wsgidav\wsgidav_app.py", line 195, in __init__
    app = mw(self, self.application, config)
  File "c:\users\ppnadmin.customers\appdata\local\programs\python\python36\lib\site-packages\wsgidav\http_authenticator.py", line 160, in __init__
    if self._authacceptdigest or self._authdefaultdigest or not self._authacceptbasic:
AttributeError: 'HTTPAuthenticator' object has no attribute '_authacceptdigest'

**Comment by n3storm** [comment]
In the first case python trace is telling you your yaml file is malformed:
`_authacceptdigest`

I am checking second post

**Comment by n3storm** [comment]
There is an error I think. I made a fix and committed a pull request.
You can check if fix works for you by installing from here: https://github.com/n3storm/wsgidav

Let's hope fix is ok and @mar10 agrees to merge.

**Comment by olafkfreund** [comment]
Thanks

**Comment by n3storm** [comment]
@olafkfreund fix has been merged into master branch.
Can you update your wsgidav installation with new code and check if this is solved?

Thanks

**Comment by olafkfreund** [comment]
Sure 👍 I did the fixt straight away after n3storm explained what was wrong manually. I( t works now.. still some problems with auth against the Microsoft AD but that's not the same problem. 
I think ( working to confirm this ) that the pypiwin32 modules is faulty against MS AD 2016.
Thanks for your fix. This works great solved my problem with DAV ( IIS 10 - webdav module is the worst.)

**Comment by n3storm** [comment]
You are welcome :)
Close the ticket please
