### ISSUE TITLE
use zope.interface for defining interfaces

### ISSUE THREAD

**Issue by loechel** [mar10/wsgidav#133]
With [zope.interface](https://pypi.org/project/zope.interface/) there is the missing link for defining clear interfaces in Python. 
Use zope.interfaces to mark classes and methods to be implemented when using wsgidav as wsgi middleware and connection own applications.

**Comment by mar10** [comment]
zope.interface is certainly a great pattern, but I am not yet convinced that the simple middleware architecture justifies to pull in an external lib (and force users to it as well?)
If there is need for a formal interface definition I currently would prefer ABCs.
