### ISSUE TITLE
hash comparison for digest auth [enhancement]

### ISSUE THREAD

**Issue by jaredrunyon** [mar10/wsgidav#137]
Hello @mar10 ,

I am currently in the process of writing custom interfaces for providers, domains, and locks.

I am currently working on the custom domain controller. However I am not going to have access to the users passwords in plain text. I will however have access to an MD5 hash stored in a users table with the user name. I have already forked the repo (and submitted a PR for previous digest auth bug fix), and am willing to add this feature to the product (if it does not exist) as well.

I do see where we are grabbing the MD5 hash from the digest auth request and could easily pass it to an interface method (if the configuration is set in the proposed `http_authenicator` setting). The interface method could look up the hash that is stored somewhere and return the hash instead of calling the `compute_digest_response` in `http_authenticator.py` line 433. Then the next line of code after this is the hash comparsion. 

PROPOSED SOLUTION (architecture):
* new optional setting for digest_auth_hash_comparsion in `http_authenticator` that is passed into the server config (default=False).
* new optional interface method for `DomainController (http_authenticator.domain_controller)`
* if setting is enabled and interface method is implemented then fetch hash from new interface method for passed in `username` instead of calling the `compute_digest_response` method based off of the `user_mapping`

I am referencing the wsgidav module in a virtual env within my own project and am hoping to not have to override any of the module code (just pip3 install all day and reference). 

I also think that hash comparison would be a great bonus to the product for enterprise level software use cases. 

Let me know  your thoughts (if you are interested in this enhancement),

JR

**Comment by mar10** [comment]
I was also thinking about creating custom domain_controllers for PAM and LDAP/AD, but did not start to go into details yet.
I am always interested in making custom providers easy to create, so if there are general extensions to API that help to achieve this, I am in.
I think a concrete approach can best be discussed with a PR?

**Comment by jaredrunyon** [comment]
That is awesome to hear! Thank you. Will def submit a PR with the enhancement. Also I am glad to hear about the LDAP/AD because I was really hoping to get this working with Single Sign On in the future.

Thanks again @mar10 !

**Comment by mar10** [comment]
Hi, sorry for the delay, and thanks for the effort. 
I didn't have much resources recently for open source in general and wsgidav in special. 
A new alpha release wouldn't hurt, maybe over the next days. 
I did not look deeply into your changes, neither did I explore LDAP, AD, or PAM so far. So I don't know how this will fit together, when I start to build middleware for that. For example I guess that MD5 is not the only hash algorithm we should support, etc.
So if I merge your changes, it will be preliminary and might change later.

**Comment by jaredrunyon** [comment]
sounds good @mar10 

My changes should only affect clients using webdav protocol with digest as the auth type and ONLY if they pass in the special config setting to get the hash from an external source by implementing the DC method.

By default no one knows about it yet so I see this not affecting anyone and the default behavior for digest auth before this feature should still be in tact. The only method I touched (besides the new setting) is the compute digest hash method. So in theory if you add new auth types to support youll have different methods to retrieve/compute those hashes independently.

If you need some help with this project (lacking time etc) I am more than happy to take on some tasks. I will be integrating deeply with this module over the next few months. I am about to start the lock and dav provider interfaces.

**Comment by mar10** [comment]
Will be part of next release

**Comment by jaredrunyon** [comment]
@mar10 I replied on email (does not look too pretty). 

Here is my config again (in pretty MD form) see questions above:
```
config = {
    'add_header_MS_Author_Via': True,  # necessary for MS Office Support
    'provider_mapping': {'demo/webdav': '/vagrant/sample_docs'},
    'verbose': 5,
    'http_authenticator': {
        'domain_controller': DomainController,
        'accept_digest': True,
        'accept_basic': False,
        'default_to_digest': True,
        'trusted_auth_header': None,
        'implements_realm_user_digest_hash': True  # enables DomainController.get_realm_user_digest_hash
    }
}
```

**Comment by mar10** [comment]
Hi,

> I have already written a custom domain controller and am passing it into my WSGI (server config file). Do these changes affect this process at all.

Your config dict should still work, but you may have to modify your DC a bit (see below).
I hope it will be straight forward. 

But since I don't know your use case, I am not sure. If you are able to share some more details, I am happy to help, or improve the API.

I also improved the config parser, so custom DCs can be initialized from the text config files. I also suggest the convention to put DC options (if any) in a separate config section

```yaml
http_authenticator:
    accept_basic: false
    accept_digest: true
    default_to_digest: true
    domain_controller: "path.to.MyCustomDomainController"

# Additional options for path.to.MyCustomDomainController only:
my_custom_dc:
    option_1: "foo"
    option_2:  42
```

> Do you see the option `implements_realm_user_digest_hash`? Does this process change at all?

I dropped this option in my exploration branch, because I had the feeling that this information should be integral part of the DC itself. So instead you would add a method `supports_http_digest_auth()` to your DC like this:

```py
class MyCustomDomainController(BaseDomainController):
    def __init__(self, wsgidav_app, config):
        super(MyCustomDomainController, self).__init__(wsgidav_app, config)
        dc_conf = config["my_custom_dc"]
        # init object members from configuration if any

    def require_authentication(self, realm, environ):
        """Return True if this realm requires authentication (grant anonymous access otherwise)."""
        return True

    def basic_auth_user(self, realm, user_name, password, environ):
        """Returns True if this user_name/password pair is valid for the realm,
        False otherwise. Used for basic authentication."""
        # ...

    def supports_http_digest_auth(self):
        # We have access to a plaintext password (or stored hash), so we can implement 
        # digest_auth_user() as well
        return True

    def digest_auth_user(self, realm, user_name, environ):
        """Computes digest hash A1 part."""
        # either grab the password and calc the A1 value:
        password = ...
       # this helper method does MD5, but we could calculate this by ourselves as well:
        return self._compute_http_digest_a1(realm, user_name, password)
        # or we return a stored digest value for this user from a DB or file...
        return lookup_a1_for_user(realm, user_name)

```

> Have any of the DomainController interface methods changed names, signatures, etc?

Yes, I cleaned up a bit and renamed some methods. It's still in the exploration branch only, but I'd be interested in your feedback, if you like.
The SimpleDomainController implements a working sample.

Please let me know if you have questions or suggestions.

**Comment by jaredrunyon** [comment]
Yes some things have definitely changed. Heres my current custom DC (with just docstrings and return statement to shorten the code):
```python
class DomainController(object):
    def __init__(self, opts):
        """
        DomainController is an interface implementation of wsgidav.dc.simple_dc.SimpleDomainController
        :param opts: dict
        """
        self.requires_authentication = True  # dictates if requires authentication
        self.implements_external_digest_hash = True  # enables get_realm_user_digest_hash

    def __repr__(self):
        return 'DC {}'.format(self.__class__.__name__)

    def get_domain_realm(self, input_url, environ):
        """
        we don't get the realm here, its already been resolved in request_resolver
        :param input_url: string
        :param environ: dict
        :return: string
        """
        return realm

    def require_authentication(self, realm_name, environ):
        """
        always return True. always requires authentication.
        :param realm_name: string
        :param environ: dict
        :return: bool
        """
        return self.requires_authentication

    def is_realm_user(self, realm_name, user_name, environ):
        """
        :param realm_name: string
        :param user_name: string
        :param environ: dict
        :return: bool
        """
        return is_realm_user

    def get_realm_user_password(self, realm_name, user_name, environ):
        """
        return None, we fetch hash stored outside of system
        used for digest authentication
        :param realm_name: string
        :param user_name: string
        :param environ: dict
        :return: string
        """
        return None

    def auth_domain_user(self, realm_name, user_name, password, environ):
        """
        used for basic authentication.
        always return false. app doesnt support Basic Authentication.
        :param realm_name: string
        :param user_name: string
        :param password: string
        :param environ: dict
        :return: bool
        """
        return False

    def get_realm_user_digest_hash(self, realm_name, user_name):
        """
        :param realm_name: string
        :param user_name: string
        :return: string, example: a4cb4d64edfe976a6df8d908aa0ff412
        """
        return digest_hash

```
Looks like I will need to change the DC methods I implemented once the release comes out. So if I understand correctly the config option is gone under `http_authenticator` and the `DC.digest_auth_user` interface method I implement will actually be in charge of providing the hash. So it has a return type of string, example: MD5 hash (a4cb4d64edfe976a6df8d908aa0ff412)? And to be clear its equivalent to A1 which is MD5(user:realm:pass)?

Also are there actually any optional config options to pass in do DC like your above config suggests? Ya I can check out the branch you have out there, sure no problem at all.

Also I will be implementing a custom interface for everything. Are you planning on applying breaking changes to all interfaces in this alpha release cycle for version 3? Now I have to go back and change my custom DC when I am currently working on the custom file content provider. If your curious I am reading/writing files via API calls

**Comment by mar10** [comment]
> Heres my current custom DC 

I added some comments (untested code):

```py
from wsgidav.dc.base_dc import BaseDomainController

# derive from base class:
class DomainController(BaseDomainController):

#    def __init__(self, opts):
    def __init__(self, wsgidav_app, config):
        # By convention we could use the __init__ signature, even if it is not required
        # wsgidav_app: the main application (WsgiDAVApp).
        # config: the main application, same as wsgidav_app.config
        self.requires_authentication = True  # dictates if requires authentication
        # self.implements_external_digest_hash = True  # enables get_realm_user_digest_hash

    # def __repr__(self):
    def __str__(self):
        return 'DC {}'.format(self.__class__.__name__)

    def get_domain_realm(self, input_url, environ):
        return realm

    def require_authentication(self, realm_name, environ):
        return self.requires_authentication

#    def is_realm_user(self, realm_name, user_name, environ):
#        not needed
#        return is_realm_user

#    def get_realm_user_password(self, realm_name, user_name, environ):
#        not needed
#        return None

#    def auth_domain_user(self, realm_name, user_name, password, environ):
    def basic_auth_user(self, realm_name, user_name, password, environ):
        # This method was renamed.
        # Also, if you set accept_basic: false, it should not get called anyways
        raise NotImplementedError

    def supports_http_digest_auth(self):
        return True

#    def get_realm_user_digest_hash(self, realm_name, user_name):
    def digest_auth_user(self, realm, user_name, environ):
        # This method was renamed and now has an 'environ' arg.
        return digest_hash
```

> Looks like I will need to change the DC methods I implemented once the release comes out. So if I understand correctly the config option is gone under `http_authenticator` and the `DC.digest_auth_user` interface method I implement will actually be in charge of providing the hash. So it has a return type of string, example: MD5 hash (a4cb4d64edfe976a6df8d908aa0ff412)? And to be clear its equivalent to A1 which is MD5(user:realm:pass)?

correct

> Also are there actually any optional config options to pass in do DC like your above config suggests? 

I don't see from your example if you need that. It is only a convention for DCs that do.
An example would be to configure the location of the credential file or auth-database login.

> Ya I can check out the branch you have out there, sure no problem at all.

> Also I will be implementing a custom interface for everything. Are you planning on applying breaking changes to all interfaces in this alpha release cycle for version 3? Now I have to go back and change my custom DC when I am currently working on the custom file content provider. If your curious I am reading/writing files via API calls

I don't have concrete plans to change the DAVProvider API right  now.
DCs were the last planned major refactoring for 3.0.

**Comment by jaredrunyon** [comment]
@mar10 thank you very very much for the detailed and thorough reply. The changes to the DC look like they will not break my current implementation. Appreciate you reaching out to me about this. Before you go to 3.0 official would you mind release one last alpha release with this DC refactoring and let me test it?

**Comment by mar10** [comment]
Your feature request was a good trigger for a long-standing overhaul of the DCs. I merged it to master now.

I think I will release one more alpha and then go beta with 3.0 soon.

**Comment by mar10** [comment]
It's there :)

**Comment by jaredrunyon** [comment]
@mar10 thank you very much!
