### ISSUE TITLE
WsgiDav==3.0.0a5

### ISSUE THREAD

**Issue by jaredrunyon** [mar10/wsgidav#140]
WsgiDav==3.0.0a5

Digest Auth currently broken in WsgiDav==3.0.0a4. Need new release to fix digest auth and add new get external digest auth hash feature.

just a reminder thanks (sorry to bug)

JR

**Comment by mar10** [comment]
Released a5, having trouble to build the msi installer though. Hope there is some time to during the next weeks.

**Comment by jaredrunyon** [comment]
thank you very much @mar10 . appreciate it.
