### ISSUE TITLE
User credentials are apparently cached server-side

### ISSUE THREAD

**Issue by Akito13** [mar10/wsgidav#143]
I set up working user authentication with the SimpleDomainController by using a corresponding .conf file. My problem is, that the server apparently saves who entered the credentials and then you don't have to put them in anymore, on every further server access. I want the credentials to be asked for every single access to the server. Is there already an option to turn off this caching somehow? Couldn't find anything even remotely related to this in the documentation.

**Comment by mar10** [comment]
Did you try to clear the browser cache and cookies?

**Comment by mar10** [comment]
Thanks!

Sending the credentials is handled by the browser. 
I don't think this can be easily achieved, without implementing a middleware that handles authentication based on cookies and sessions.
See here for some info:
https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication
This is currently on the road map, but I am open to suggestions how this could be implemented easily (or pull-requests of course)
