### ISSUE TITLE
dynamic provider registration

### ISSUE THREAD

**Issue by jaredrunyon** [mar10/wsgidav#148]
Hello @mar10 ,

Hope all is well. I have something I am trying to achieve with latest build (v3.0.0) of WsgiDAV and wanted to run some scenarios by you.

Currently I am registering providers as follows:
```
config = {
    'provider_mapping': {
        'my_realm/custom': Provider(),
        'my_realm/custom2': Provider(),
        'my_realm2/custom': Provider()
    }
}
```

I would like to know if there is a way I can register a `Provider` interface to to work for all `provider_mapping` entries with out me having to register them. I will be needing to register at least 100 maybe 200 providers. Loading 200 provider entries may not be the best thing to do in a config file for me. Not sure how that will effect the memory of the application? What happens when you register a provider? Will having 200 registered providers effect anything in terms of the WsgiDav app or performance?

Also here is my `DomainController` interface `get_domain_realm` method:
```
    def get_domain_realm(self, path_info, environ):
        """
        Resolve a relative url to the appropriate realm name.
        :param path_info: string
        :param environ: dict
        :return: string
        """
        realm = self._calc_realm_from_path_provider(path_info, environ)
        return realm
```

This appears to be where the magic happens (at least resolving urls to realms). However the providers would need to be dynamically set here maybe (if possible)?

Ultimately I would like to not have to have 200 registered providers in the config file. I would like to have that `get_domain_realm` method resolve the path and check the DB to see if that realm is able to be used (I am already doing this successfully), however if I do not have the realm registered to a provider then I obviously dont have a provider?

Any tips on how to get all realms to be registered to the same provider without having to register them?

Thanks,

JR

**Comment by mar10** [comment]
How about registering one single provider for the `/` share only?
Your provider could then inspect path_info to decide what to serve.
Also, the `simple_dc.py` is only a sample. You could implement and use a modified version if it helps

**Comment by jaredrunyon** [comment]
I have a custom domain controller interface already implemented. I have tried registering just the `/` share only. 
```
    def get_domain_realm(self, path_info, environ):
        """
        Resolve a relative url to the appropriate realm name.
        :param path_info: string
        :param environ: dict
        :return: string
        """
        realm = self.get_realm_from_path(path_info, environ)  # returns realm if valid else None
        return realm
```
The issue I run into though is even after I run the logic to inspect the path and say yes this realm is valid and return the realm name, the request resolver (I think request resolver) or somewhere like that thinks that the realm is not registered so there is nothing to serve up. My question is does the realm have to actually be registered in order for the flow to work. I could hack the provider interface and set the realm to '/' but have another variable like 'real_realm' or something, but seems hacky.

**Comment by jaredrunyon** [comment]
I have to return '/' for the provider to be called and then the request passes in '/' for the realm and it does it thing. But I need the real realm to passed into the provider interface but if the realm is not registered then the realm has no provider to go to.

**Comment by jaredrunyon** [comment]
looks like `path` is passed into the provider interface from the `get_domain_realm` method.
on the `Provider`  interface self.share_path is null but I can set it there on `Provider` instantiation and be all good. Thank you very much.

**Comment by jaredrunyon** [comment]
I can make it work this way but its def a work around. I have to always check path to see if its the same as realm name and look up / instead but thx i might go down this route closing issue. Wat about the memory question though? Have you tried registering a large amount of providers before?

Sent from my iPhone

On Mar 24, 2019, at 12:49 PM, Martin Wendt <notifications@github.com<mailto:notifications@github.com>> wrote:


How about registering one single provider for the / share only?
Your provider could then inspect path_info to decide what to serve.
Also, the simple_dc.py is only a sample. You could implement and use a modified version if it helps
