### ISSUE TITLE
wsgidav.response_headers only added to GET/HEAD requests

### ISSUE THREAD

**Issue by SteffenDE** [mar10/wsgidav#154]
The custom headers should be included in every response, not only when using GET/HEAD.

https://github.com/mar10/wsgidav/blob/08768f6c4364021a3b1f4da8866960469e7e78a9/wsgidav/request_server.py#L1593-L1598

Also, `res.finalize_headers()` should be called.

**Comment by mar10** [comment]
Can you give a use case? #90 seems to be ok with setting headers on *every* request. I am not sure if this is always the case and we might need to extend the configuration?

**Comment by SteffenDE** [comment]
#90 talked about the "Access-Control-Allow-Origin" header. Adding this header to the response_headers configuration currently does not help at all, as for CORS to work (https://developer.mozilla.org/de/docs/Web/HTTP/CORS), the headers must be added to every request. Currently, they are only added to GET and HEAD requests. CORS is actually a little bit more complex, so maybe there should be **a middleware for that**, but still I think response_headers should be applied to every request.

Trying to do a CORS request from the browser:
<img width="1080" alt="Bildschirmfoto 2019-05-09 um 21 50 57" src="https://user-images.githubusercontent.com/4116351/57482480-03c62b80-72a5-11e9-80f5-355b16b37f5d.png">
response_headers added to GET:
<img width="525" alt="Bildschirmfoto 2019-05-09 um 21 51 12" src="https://user-images.githubusercontent.com/4116351/57482483-07f24900-72a5-11e9-9962-e1a63edb41de.png">
response_headers not added to OPTIONS:
<img width="551" alt="Bildschirmfoto 2019-05-09 um 21 51 20" src="https://user-images.githubusercontent.com/4116351/57482487-0a54a300-72a5-11e9-90e8-2d6c5e30ea20.png">
response_headers not added to PUT:
<img width="522" alt="Bildschirmfoto 2019-05-09 um 21 51 32" src="https://user-images.githubusercontent.com/4116351/57482494-0e80c080-72a5-11e9-89ee-af931554a0c1.png">

For my use-case I actually tried to achieve setting a cookie from a Directory Controller (verifying basic auth credentials on every request is very expensive using modern password hash algorithms) and some clients support sending cookies instead. I "fixed" this by caching a hash of the username+password combination in memory using a faster hash algorithm (blake2) and storing that hash (and the auth result) for 60 seconds. Therefore, clients that send many requests at once (like macOS Finder when unpacking a ZIP file on a WebDAV drive) does not require hashing the password all the time.

**Comment by mar10** [comment]
Started a branch: [append_custom_headers](https://github.com/mar10/wsgidav/tree/append_custom_headers)
