### ISSUE TITLE
Which to choose? 3.x or 2.x?

### ISSUE THREAD

**Issue by killing** [mar10/wsgidav#160]
Hi,

First of all thank you for this nice project.

I'm a developer from the Seafile project (https://www.seafile.com). We've been using wsgidav for our webdav server for a few years. Except for some minor issues, it works quite well. (I assume some of the issues have been fixed in the latest version. It's our fault to not upgrade.) Recently we are considering upgrading to a new version of wsgidav. But we are not sure which version to base on. The 3.x version looks new but 2.x version is marked a more "stable". I assume that the 3.x version is the future so I prefer to use 3.x. But how "unstable" or stable is the 3.x version?

Suggestions are welcome :-)

Thanks in advance.

Jonathan

**Comment by mar10** [comment]
Hi,
Nice to hear from you and your project!
I would suggest to use 3.0, it is in the wild for some month now and 2.x is going to fade out.
(Don't forget to send issues, suggestions, or pull requests :grr

**Comment by killing** [comment]
Hi @mar10 

Thank you for the answer! So we'll proceed with 3.x.
