### ISSUE TITLE
RedisLockManager

### ISSUE THREAD

**Issue by rootRaider** [mar10/wsgidav#163]
Hello @mar10 ,

I wanted to drop you a line about lock managers.

 Do we have any documentation on custom lock managers? I have kind of figured that looking at the default LockManager might be the best way to implement a custom lock manager. The only reason that I am interested in creating a custom lock manager is because our system is going to be load balanced with multiple servers so the lock storage needs to be in one centralized place.

If I was able to manipulate the current LockManager by adding in a configuration option like "Save Lock Data In Redis" or something like that would you be interested in having that be a part of the project?

Also I see that there are two LockMangers right now available, one uses Shelve? Also I am asking if there is already a way available to accomplish what I am trying to do? Can we get lock storage data in a centralized place currently or do I need to write a custom LockManager?

Let me know your thoughts.

Thanks,

JR

**Comment by mar10** [comment]
Hi,

the `LockManager` should not need to be changed to support new storage types, at least this is the idea. 
It uses the `LockStorage` instance that you pass to the constructor instead.

I don't think we should add special behavior to the in-memory `LockStorageDict`. Instead you could create a new `LockStorageRedis` that implements that interface.

(The `LockStorageShelf` is not really useful, but may serve as an example. There is no requirement to derive from `LockStoragDict` though.)

If you have working code, we may add it to this repo.

**Comment by rootRaider** [comment]
So the interface that you implement is the LockStorage?

So on the configuration file you pass in the LockStorage instance into the default LockManager?

On config "wsgi.py" what is the variable name and how do you declare it?

Can you provide me an example? (current wsgi.py)
```
config = {
    'add_header_MS_Author_Via': True,  # necessary for MS Office Support
    'provider_mapping': {'/': CustomProvider()},
    'verbose': verbose_level,
    'http_authenticator': {
        'domain_controller': CustomDomainController
    },
    # what do i do here for lock storage and lock manager
    'lock_storage': CustomLockStorage  # will this get passed into the LockManager?
}
```

**Comment by mar10** [comment]
> So the interface that you implement is the LockStorage?

right

> So on the configuration file you pass in the LockStorage instance into the default LockManager?

yes

> On config "wsgi.py" what is the variable name and how do you declare it?

The configuration name is a bit misleading. You configure the LockStorage by passing it to the configuration by the name "lock_manager".  
This LockStorage is then passed to the `LockManager` constructor. Here is snippet of the initialization code in `wsgidav_app.py`.

    lock_storage = config.get("lock_manager")  # the config name is misleading here
    if lock_storage is True:
        lock_storage = LockStorageDict()

    if not lock_storage:
        self.lock_manager = None
    else:
        self.lock_manager = LockManager(lock_storage)

**Comment by rootRaider** [comment]
I will try this. Thank you very much.
