### ISSUE TITLE
Wrong separator on Allow values

### ISSUE THREAD

**Issue by BSipos-RKF** [mar10/wsgidav#164]
Currently all of the HTTP responses include an "Allow" header with values separated by spaces instead of commas as required by [RFC7231](https://tools.ietf.org/html/rfc7231#section-7.4.1). 

This is a simple fix in `request_server.py` to change:

    -        headers.append( ("Allow", " ".join(allow)) )
    +        headers.append( ("Allow", ", ".join(allow)) )

**Comment by mar10** [comment]
Hi,
strange that this protocol violation went unnoticed since years. Did you observe any problems?

**Comment by BSipos-RKF** [comment]
I did not see an issue in any end use application. I only noticed because the werkzeug function `werkzeug.http.parse_set_header` was failing to decode the method names.
