### ISSUE TITLE
cannot import name 'collections_abc' from 'six.moves' (unknown location)

### ISSUE THREAD

**Issue by palmfighter** [mar10/wsgidav#172]
Hi,

I followed this document:
https://www.vultr.com/docs/deploying-webdav-on-debian-10-using-wsgidav

to install WSGIDAV on my Debian server. When trying to start the server I see this:

sudo wsgidav -c /usr/local/etc/wsgidav.yaml
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 6, in <module>
    from wsgidav.server.server_cli import run
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/server/server_cli.py", line 38, in <module>
    from wsgidav import __version__, util
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/util.py", line 12, in <module>
    from wsgidav import compat
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/compat.py", line 15, in <module>
    from six.moves import (
ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)

I cannot seem to find the issue.

**Comment by mar10** [comment]
This may be a problem introduced with 3.0.2 https://github.com/mar10/wsgidav/commit/9776709b4ced9b9ffb4e7c09765ff278013f3bb9 

Could you do a pip show six: which `six` version is installed? If it's not 1.13, does `pip install -U six`help?
(Or does it work when you use WsigiDAV 3.0.1?)

**Comment by palmfighter** [comment]
Hi,
thanks for the quick reply!

the output for pip show six is:
Name: six
Version: 1.13.0
Summary: Python 2 and 3 compatibility utilities
Home-page: https://github.com/benjaminp/six
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Required-by: 

-----
btw it wasn't installed.. so when running sudo pop install -U six it did install the application. I tried running the command: sudo wsgidav -c /usr/local/etc/wsgidav.yaml again but no luck. 

thanks!

**Comment by mar10** [comment]
I assume you have WsgiDAV installed into Python 3.7 (that's what the stack trace says.)
Please run `wsgidav --version -v` to confirm.

The `pip show six` prints "Location: /usr/local/lib/python2.7/dist-packages"
So I think you where using another Python installation there.
Try `python3 -m pip show six` (and `python3 -m pip install six` if the version is < 1.13)

**Comment by palmfighter** [comment]
Hi Martin,

thanks again, please see the traces below:

wsgidav --version -v
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 6, in <module>
    from wsgidav.server.server_cli import run
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/server/server_cli.py", line 38, in <module>
    from wsgidav import __version__, util
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/util.py", line 12, in <module>
    from wsgidav import compat
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/compat.py", line 15, in <module>
    from six.moves import (
ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)
---------
python3 -m pip show six
Name: six
Version: 1.12.0
Summary: Python 2 and 3 compatibility utilities
Home-page: https://github.com/benjaminp/six
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: WsgiDAV, cheroot
----------
python3 -m pip install six
Requirement already satisfied: six in /usr/lib/python3/dist-packages (1.12.0)

Not sure how to move it to 1.13? I guess we need six 1.13?

**Comment by mar10** [comment]
Sorry, `python3 -m pip install -U six` (with -U) should do the update

**Comment by palmfighter** [comment]
Ok updated PIP now to 1.13:

`XXX@XXX:~$ wsgidav --version -v
WsgiDAV/3.0.2 Python/3.7.3 Linux-4.19.0-6-amd64-x86_64-with-debian-10.2`

`XXX@XXX:~$ python3 -m pip show six
Name: six
Version: 1.13.0
Summary: Python 2 and 3 compatibility utilities
Home-page: https://github.com/benjaminp/six
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: WsgiDAV, cheroot`

`XXX@XXX:~$ sudo wsgidav -c /usr/local/etc/wsgidav.yaml
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/server/server_cli.py", line 806, in run
    app = WsgiDAVApp(config)
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/wsgidav_app.py", line 179, in __init__
    self.add_provider(share, provider)
  File "/usr/local/lib/python3.7/dist-packages/wsgidav/wsgidav_app.py", line 323, in add_provider
    raise ValueError("Invalid provider {}".format(provider))
ValueError: Invalid provider None`

so a new error, I guess this is for the authentication, let me check if I didn't make a mistake there...

**Comment by mar10** [comment]
Yes that looks like an unrelated configuration problem in the yaml.

Concerning this issue, I will update the requirements for six in release 3.0.3.
