### ISSUE TITLE
ImportError: cannot import name collections_abc

### ISSUE THREAD

**Issue by peerless2012** [mar10/wsgidav#174]
Hi, i install for 3.0.3 and this is the error when test the wsgidav,

```
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 5, in <module>
    from wsgidav.server.server_cli import run
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/server/server_cli.py", line 38, in <module>
    from wsgidav import __version__, util
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/util.py", line 12, in <module>
    from wsgidav import compat
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/compat.py", line 15, in <module>
    from six.moves import (
ImportError: cannot import name collections_abc
```
Not: I test install 3.0.2 and use #172 to resolve the error and run, but when i reinstall with 3.0.3, the above error print.

Here is other version:
```
python3 -m pip show six
Name: six
Version: 1.14.0
Summary: Python 2 and 3 compatibility utilities
Home-page: https://github.com/benjaminp/six
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: WsgiDAV, cheroot

```

**Comment by mar10** [comment]
3.0.3 is not yet released, did you try the latest code from master, e.g.

    pip install git+https://github.com/mar10/wsgidav.git@master

**Comment by peerless2012** [comment]
Itest it just now，still not work.
`wsgidav --version -v
Traceback (most recent call last):
  File "/home/pi/.local/bin/wsgidav", line 5, in <module>
    from wsgidav.server.server_cli import run
  File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/server/server_cli.py", line 38, in <module>
    from wsgidav import __version__, util
  File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/util.py", line 12, in <module>
    from wsgidav import compat
  File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/compat.py", line 15, in <module>
    from six.moves import (
ImportError: cannot import name collections_abc`

**Comment by mar10** [comment]
I assume you installed to a macOS system Python?
In this case the system's six is not updated to 1.13+. You can either do this manually or install it to a virtual env instead, as described in the docs.

Anyway: I added a fix that removes the dependency, so v3.0.3 it should work now with a six version 1.12.
Until 3.0.3 is released, this could work for you:
```
sudo pip install git+https://github.com/mar10/wsgidav -U
```

**Comment by peerless2012** [comment]
I install it on a rsapberry, and the six is 1.14.0.

**Comment by mar10** [comment]
Can you share more information like the output of your installation command and `pip list`? What does `which wsgidav` print?

**Comment by peerless2012** [comment]
`pip install cheroot
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cheroot
  Downloading cheroot-8.3.0-py2.py3-none-any.whl (86 kB)
     |███▉                            | 10 kB 7.6 MB/s eta 0     |███████▋                        | 20 kB 338 kB/s eta 0     |███████████▍                    | 30 kB 489 kB/s eta 0     |███████████████▏                | 40 kB 342 kB/s eta 0     |███████████████████             | 51 kB 420 kB/s eta 0     |██████████████████████▉         | 61 kB 500 kB/s eta 0     |██████████████████████████▋     | 71 kB 574 kB/s eta 0     |██████████████████████████████▍ | 81 kB 648 kB/s eta 0     |████████████████████████████████| 86 kB 214 kB/s
Requirement already satisfied: backports.functools-lru-cache; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from cheroot) (1.5)
Collecting jaraco.functools
  Downloading https://www.piwheels.org/simple/jaraco-functools/jaraco.functools-3.0.0-py2.py3-none-any.whl (6.7 kB)
ERROR: Package 'jaraco.functools' requires a different Python: 2.7.16 not in '>=3.6'`

**Comment by peerless2012** [comment]
`pi@raspberrypi:~ $ pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                       Version
----------------------------- -----------
arandr                        0.1.9
asn1crypto                    0.24.0
automationhat                 0.2.0
backports.functools-lru-cache 1.5
beautifulsoup4                4.7.1
blinker                       1.4
blinkt                        0.1.2
buttonshim                    0.0.2
Cap1xxx                       0.1.3
certifi                       2018.8.24
chardet                       3.0.4
Click                         7.0
colorama                      0.3.7
colorzero                     1.1
configparser                  3.5.0b2
cookies                       2.2.1
cryptography                  2.6.1
defusedxml                    0.6.0
dnspython                     1.16.0
drumhat                       0.1.0
entrypoints                   0.3
enum34                        1.1.6
envirophat                    1.0.0
ExplorerHAT                   0.4.2
Flask                         1.0.2
fourletterphat                0.1.0
funcsigs                      1.0.2
gpg                           1.12.0
gpiozero                      1.5.1
html5lib                      1.0.1
idna                          2.6
ipaddress                     1.0.17
itsdangerous                  0.24
Jinja2                        2.10
json5                         0.9.1
keyring                       17.1.1
keyrings.alt                  3.1.1
lxml                          4.3.2
MarkupSafe                    1.1.0
microdotphat                  0.2.1
mock                          2.0.0
mote                          0.0.4
motephat                      0.0.2
numpy                         1.16.2
oauthlib                      2.1.0
olefile                       0.46
pantilthat                    0.0.7
pbr                           4.2.0
phatbeat                      0.1.1
pianohat                      0.1.0
picamera                      1.13
picraft                       1.0
piglow                        1.2.5
pigpio                        1.44
Pillow                        5.4.1
pip                           20.0.2
psutil                        5.5.1
pycairo                       1.16.2
pycrypto                      2.6.1
pygame                        1.9.4.post1
PyGObject                     3.30.4
pyinotify                     0.9.6
PyJWT                         1.7.0
pyOpenSSL                     19.0.0
pyserial                      3.4
pyxdg                         0.25
PyYAML                        5.3
rainbowhat                    0.1.0
requests                      2.21.0
requests-oauthlib             1.0.0
responses                     0.9.0
RPi.GPIO                      0.7.0
RTIMULib                      7.2.1
scrollphat                    0.0.7
scrollphathd                  1.2.1
SecretStorage                 2.3.1
sense-hat                     2.2.0
setuptools                    40.8.0
simplejson                    3.16.0
six                           1.12.0
skywriter                     0.0.7
sn3218                        1.2.7
soupsieve                     1.8
spidev                        3.4
touchphat                     0.0.1
twython                       3.7.0
unicornhathd                  0.0.4
urllib3                       1.24.1
webencodings                  0.5.1
Werkzeug                      0.14.1
wheel                         0.32.3
WsgiDAV                       3.0.2`

**Comment by mar10** [comment]
```
sudo pip install git+https://github.com/mar10/wsgidav -U
```
?

**Comment by peerless2012** [comment]
`pi@raspberrypi:~ $ sudo pip install git+https://github.com/mar10/wsgidav -U
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/mar10/wsgidav
  Cloning https://github.com/mar10/wsgidav to /tmp/pip-req-build-CKzzXG
  Running command git clone -q https://github.com/mar10/wsgidav /tmp/pip-req-build-CKzzXG
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python2.7/dist-packages (from WsgiDAV==3.0.3) (5.3)
Requirem`

After this，i use pip list，the wsgidav is still 3.0.2

**Comment by mar10** [comment]
Seems your output is incomplete, also please use three ticks instead of one to format the output in this comments.

**Comment by mar10** [comment]
also: what does `which wsgidav` print?

**Comment by peerless2012** [comment]
'''
pi@raspberrypi:~ $ sudo pip install git+https://github.com/mar10/wsgidav -U
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/mar10/wsgidav
  Cloning https://github.com/mar10/wsgidav to /tmp/pip-req-build-CKzzXG
  Running command git clone -q https://github.com/mar10/wsgidav /tmp/pip-req-build-CKzzXG
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python2.7/dist-packages (from WsgiDAV==3.0.3) (5.3)
Requirement already satisfied, skipping upgrade: Jinja2 in /usr/lib/python2.7/dist-packages (from WsgiDAV==3.0.3) (2.10)Requirement already satisfied, skipping upgrade: defusedxml in /usr/local/lib/python2.7/dist-packages (from WsgiDAV==3.0.3) (0.6.0)
Requirement already satisfied, skipping upgrade: json5 in /usr/local/lib/python2.7/dist-packages (from WsgiDAV==3.0.3) (0.9.1)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-packages (from WsgiDAV==3.0.3) (1.12.0)
Building wheels for collected packages: WsgiDAV
  Building wheel for WsgiDAV (PEP 517) ... done
  Created wheel for WsgiDAV: filename=WsgiDAV-3.0.3-py2.py3-none-any.whl size=169532 sha256=7c205a804c14b3cee095a8141b05277a7b7ff6cb86cc0f29302dd464437f5722
  Stored in directory: /tmp/pip-ephem-wheel-cache-s1jv5K/wheels/45/bb/eb/f41d9d9a9cfaa155728c48076e2ca8422765f68b4ec64ed8d0
Successfully built WsgiDAV
Installing collected packages: WsgiDAV
  Attempting uninstall: WsgiDAV
    Found existing installation: WsgiDAV 3.0.3
    Uninstalling WsgiDAV-3.0.3:
      Successfully uninstalled WsgiDAV-3.0.3
Successfully installed WsgiDAV-3.0.3
pi@raspberrypi:~ $ wsgidav --version -v                     Traceback (most recent call last):
  File "/home/pi/.local/bin/wsgidav", line 5, in <module>
    from wsgidav.server.server_cli import run
  File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/server/server_cli.py", line 38, in <module>
    from wsgidav import __version__, util
  File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/util.py", line 12, in <module>
    from wsgidav import compat
  File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/compat.py", line 15, in <module>
    from six.moves import (
ImportError: cannot import name collections_abc
'''

**Comment by peerless2012** [comment]
`pi@raspberrypi:~ $ which wsgidav
/home/pi/.local/bin/wsgidav`

**Comment by mar10** [comment]
It seems that you install to `/home/pi/.local/bin/wsgidav` but the libs are searched in `/usr/local/lib/python2.7/dist-packages `
Could you try
```
sudo pip install -U six
```
and share the output?

**Comment by peerless2012** [comment]
`pi@raspberrypi:~ $ sudo pip install -U six
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six
  Attempting uninstall: six
    Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
Successfully installed six-1.14.0`
