### ISSUE TITLE
How to add HTTP-SASL?

### ISSUE THREAD

**Issue by vanrein** [mar10/wsgidav#178]
Sorry to be a bit active :)

I've been looking if it would be difficult to add our [HTTP-SASL](http://internetwide.org/blog/2018/11/15/somethings-cooking-4.html) with [current I-D](https://tools.ietf.org/html/draft-vanrein-httpauth-sasl) proposed mechanism.  That being strictly authentication, I am wondering if it should go into the `http_authenticator` class.  I ran into the `dc` backend which is pluggable, yet conflates authentication with authorisation, so not a perfect fit.

Our project defines an [ACL mechanism](http://donai.arpa2.net/acl.html) that I would use for authorisation, but it would not make sense to everyone to force the combination with HTTP SASL, which could be more generally useful IMHO.  I might make a separate pluggable ACL as part of a proposed HTTP SASL plugin, but that sounds like I'd be outstepping my boundaries.  One reason for this ACL mechanism is that it welcomes foreign accounts, which combines well with our proposed [SASL mechanism for realm crossover](https://tools.ietf.org/html/draft-vanrein-diameter-sasl) named SXOVER.

What do you suggest?  Would you be open to (a branch or PR with) an extension to the `http_authenticator` with SASL authentication, in spite of its early stage?  Or should it be part of a `dc` backend?  Do you see value in splitting authentication from authorisation, at least in some `dc` backends, or should I create a tight bond between HTTP SASL and the ACL idea in our ARPA2 projects?

FYI, some [background](http://internetwide.org/blog/2016/06/24/iwo-phases.html) to our project and why this may seem like a bit much.  For us, [Reservoir](http://internetwide.org/blog/2020/02/16/reservoir-reaching-out.html) including `wsgidav` forms a good demonstration of our conceptual work on InternetWide Identity with end users back at the helm.

**Comment by mar10** [comment]
Sorry for being a bit inactive ;)
Your projects look really interesting, even if I did not have time to dive into deeper yet.

> WSGI middleware that demonstrates how HTTP SASL can be a layer that can mount on any WSGI service;

Custom middleware can be configured, but I assume that is not enough?

I admit that I don't understand enough about the details, to offer a recommendation. Generally I am open to extending the architecture, as long as it is concise and general. I.e. optimally changes to http_authenticator and DC should make implementations of SASL *or other protocols* easier.

A fork with a sample implementation may be a good starting point for discussion or prototype.
Please understand that I currently don't have much resources to put into this though, and I cannot guarantee that a PR it will finally be accepted.
