### ISSUE TITLE
Uploading files results in 0 bytes

### ISSUE THREAD

**Issue by jalohse** [mar10/wsgidav#179]
I recently updated my v1.3.0 `wsgidav` to v2.4.1. All functions seem to work except for uploading a file. The file always ends up being 0 bytes after upload. There are no stack traces, and I have been trying to track down where the issue happens, but I am lost. I have included the logs from `wsgidav` [here](https://github.com/mar10/wsgidav/files/4331069/webdavlogs.txt). If anyone could point me in the correct direction, it would be much appreciated! I am not sure if it is a configuration issue or a code issue. I can provide more information if needed.

**Comment by mar10** [comment]
Hi,
this does not look like a wsgidav log file. 
Could you run wsgidav from the console with `-vv` option, perform an upload, and share those logs? 
What client are you using?

**Comment by jalohse** [comment]
Hi,
We are running wsgidav in Docker in a Django 1.11 project with a uwsgi server backend. We have subclassed the project a little to work with our file system. I increased all the logging to max and the result is [here](https://github.com/mar10/wsgidav/files/4338550/webdavlogs.txt).

I did find that files were successfully upload in version 2.0.0, so it seems to be some change in between the two versions.

**Comment by mar10** [comment]
I don't know what *subclassed the project a little* means in detail, or what these lines do:
```log
webdav_1           | [I 2020-03-16 09:54:04,348 pid=31 ftphosting.celery] Configuring Celery/Sentry integration
webdav_1           | [D 2020-03-16 09:54:04,348 pid=31 raven.base.Client] Configuring Raven for host: None
webdav_1           | [I 2020-03-16 09:54:04,350 pid=31 raven.base.Client] Raven is not configured (logging is disabled). Please see the documentation for more information.
```

Anyway, the log suggests that the WebDAV clients sends PUT request with **a length of 0 bytes** (and succeeded):
```
webdav_1           | [I 2020-03-16 09:54:04,627 pid=31 wsgidav.debug_filter] PUT Request ---
webdav_1           | [I 2020-03-16 09:54:04,628 pid=31 wsgidav.debug_filter] REQUEST_METHOD      : 'PUT'
webdav_1           | [I 2020-03-16 09:54:04,629 pid=31 wsgidav.debug_filter] REQUEST_URI         : '/webdav/test.mp4'
webdav_1           | [I 2020-03-16 09:54:04,630 pid=31 wsgidav.debug_filter] PATH_INFO           : '/test.mp4'
webdav_1           | [I 2020-03-16 09:54:04,630 pid=31 wsgidav.debug_filter] QUERY_STRING        : ''
webdav_1           | [I 2020-03-16 09:54:04,631 pid=31 wsgidav.debug_filter] SERVER_NAME         : '9bd3b2a7b417'
webdav_1           | [I 2020-03-16 09:54:04,632 pid=31 wsgidav.debug_filter] UWSGI_ROUTER        : 'http'
webdav_1           | [I 2020-03-16 09:54:04,632 pid=31 wsgidav.debug_filter] REMOTE_ADDR         : '172.26.0.22'
webdav_1           | [I 2020-03-16 09:54:04,633 pid=31 wsgidav.debug_filter] HTTP_HOST           : 'test.dev.smartfile.com'
webdav_1           | [I 2020-03-16 09:54:04,633 pid=31 wsgidav.debug_filter] CONTENT_LENGTH      : '0'
webdav_1           | [I 2020-03-16 09:54:04,635 pid=31 wsgidav.debug_filter] HTTP_USER_AGENT     : 'WebDAVFS/3.0.0 (03008000) Darwin/19.3.0 (x86_64)'
webdav_1           | [I 2020-03-16 09:54:04,635 pid=31 wsgidav.debug_filter] HTTP_X_FORWARDED_PROTO: 'https'
webdav_1           | [I 2020-03-16 09:54:04,636 pid=31 wsgidav.debug_filter]
webdav_1           |
webdav_1           | [D 2020-03-16 09:54:05,645 pid=31 wsgidav.ftphosting.webdav.fs_dav_provider] beginWrite: /test.mp4, wb
webdav_1           | [I 2020-03-16 09:54:05,742 pid=31 wsgidav.request_server] PUT: Content-Length == 0. Creating empty file...
webdav_1           | [I 2020-03-16 09:54:05,977 pid=31 wsgidav.wsgidav_app] 172.26.0.22 - administrator - [2020-03-16 13:54:05] "PUT /test.mp4" length=0, connection="close", agent="WebDAVFS/3.0.0 (03008000) Darwin/19.3.0 (x86_64)", elap=1.350sec -> 201 Created
webdav_1           | [I 2020-03-16 09:54:05,977 pid=31 wsgidav.debug_filter] <140612531648256> ---PUT  Response(201 Created): ---
```

This file is then Locked, Unlocked, Locked, Unlocked, and *then Deleted** by that client.
I don't know if this is a normal sequence for that client, maybe it did not receive the expected responses for previous requests and so cleanup.

Can you 
- try with the latest WsgiDAV 3.0.2. Older versions are not really supported any more
- compare the sequence if you switch back to WsgiDAV 1
- try with another client

**Comment by jalohse** [comment]
We are using [Celery](http://www.celeryproject.org/) for asynchronous tasks and Sentry and Raven are for logging. It should not be affecting the issue. 

Here are the logs with [version 1.3](https://github.com/mar10/wsgidav/files/4349326/webdavlogs1.txt). The same pattern occurs here. I had assumed this was just how webdav worked, but it seems like that is not the case.

For more context on our implementation, we have custom implementations of `FileResource`, `FolderResource`, `VirtualFileResource`, `VirtualFolderResource`, and `FilesystemProvider`. These implementations just ensure that the files and folders are being added into our version of the file system, while keeping the base functionality from `wsgidav`. 

Since we aren't seeing the issue with 2.0.0, we were able to get our Python 3 version working. I understand that these versions aren't supported, so it is fine to close the issue if you would like.

**Comment by mar10** [comment]
ok, thank you!
