### ISSUE TITLE
request: seteuid() functionality

### ISSUE THREAD

**Issue by klaird** [mar10/wsgidav#184]
I've been trying for decades to get away from Samba for Windows users.  Today I circled back to WebDAV and tried wsgidav.  It's wonderful!

I did need to add a few lines in order to seteuid()/setegid() as the authenticated user (and back to root).  I would love to see this as a standard feature.  I know there are others out there looking for this functionality.

Thank you!

**Comment by mar10** [comment]
Thanks, I am open to this.
Do you have a concrete implementation proposal, that you coud create as PR?

**Comment by kylerlaird** [comment]
I have a concrete implementation.  (It's out for testing now.)  I don't have a concrete proposal, though.  I wouldn't recommend incorporating the approach that I took; there must be a better way to do it.  However, I'll show what does seem to work for me.

Here is what I added to request_server.py:
        user_name = environ.get('wsgidav.auth.user_name')
        provider.root_folder_path = '/home/' + user_name
        with self.SetUID(user_name):
            # Below is the original call.
            app_iter = provider.custom_request_handler(environ, start_response, method)

    class SetUID:
        def __init__(self, user_name):
            self.user_pwd = pwd.getpwnam(user_name)

        def __enter__(self):
            os.setegid(self.user_pwd.pw_gid)
            os.seteuid(self.user_pwd.pw_uid)

        def __exit__(self, type, value, traceback):
            os.seteuid(0)
            os.setegid(0)


Again, this is a terribly naive approach that I whipped up in a few minutes after getting wsgidav running for the first time.  Someone who knows wsgidav will certainly have a better approach that includes a selectable option, error checking, etc.

wsgidav could be a clean answer to an old request.
https://unix.stackexchange.com/questions/123001/is-there-a-multi-user-webdav-server-available-for-linux

**Comment by mar10** [comment]
This would be an interesting new feature (good complement/addition to #107, #161, ...).
Currently I focus on other side projects, but maybe I pick up here later.

**Comment by sk1p** [comment]
@mar10 Thanks for posting your approach! I tried this out, and in practice it turns out it will only work when using a single-threaded multi-process approach - otherwise, multiple threads interfere with each other (which then causes `EPERM` errors).

I used gunicorn with the following options, just for testing:

```patch
@@ -813,7 +823,8 @@ def _run_gunicorn(app, config, mode):
 
     options = {
         "bind": "{}:{}".format(config['host'], config['port']),
-        "threads": 50,
+        "worker_class": "sync",
+        "workers": 8,
         "timeout": 1200
     }
     GunicornApplication(app, options).run()
```

I'm also setting the auxiliary groups and doing some error handling, so the context manager looks something like this:

```python
@contextlib.contextmanager
def setuid(user_name):
    old_groups = os.getgroups()
    user_pwd = pwd.getpwnam(user_name)
    user_groups = [g.gr_gid for g in grp.getgrall() if user_name in g.gr_mem]
    user_groups.insert(0, user_pwd.pw_gid)
    try:
        try:
            os.setegid(user_pwd.pw_gid)
            os.setgroups(user_groups)
            os.seteuid(user_pwd.pw_uid)
        except Exception as e:
            _logger.error("error setting gid/uid/groups: %r", str(e))
            _logger.error("groups: %r", user_groups)
            _logger.error("gid: %d, uid: %d", user_pwd.pw_gid, user_pwd.pw_uid)
            raise
        yield
    finally:
        os.setegid(0)
        os.seteuid(0)
        os.setgroups(old_groups)
```

/cc @uellue
