### ISSUE TITLE
Issue with listening music or watch videos in mac os and Android device Raising DAVError 404 Not Found

### ISSUE THREAD

**Issue by Daeamon** [mar10/wsgidav#188]
Hello, when i trying watch videos or listening music, after a while, playback stops and cause error in log Raising DAVError 404 Not Found, help me please to resolve this problem.
Last file what a caused error is 03. Basics of Xcode.mp4.
[wsgidav.log](https://github.com/mar10/wsgidav/files/5006361/wsgidav.log)

**Comment by mar10** [comment]
Hi,
can yo explain a bit more what you are doing. I assume this
- run wsgidav from command line with `-vv` on some server
- Share a folder with mp4 files on that server
- Open a client on your local machine
- Everything works in general except for some intermittent errors

is that correct?
It looks like the 404s are from reading some properties

- Can you attach a log that only has `-v` or no `-v` at all, maybe we see some pattern in theses overviews
- what client / player are you using
- can you send the command line and configuration file

**Comment by Daeamon** [comment]
[wsgidav.yaml.txt](https://github.com/mar10/wsgidav/files/5009991/wsgidav.yaml.txt)
Yes, everything work in general except for some intermittent errors.
On Mac Book I use the built-in client. On Android device, I am using Neutron Music Player which supports WebDAV through curl.
