### ISSUE TITLE
Feature request: Ability to specify a custom location for `:dir_browser`

### ISSUE THREAD

**Issue by dom111** [mar10/wsgidav#191]
Hey,

I've [recently had an issue raised on dom111/webdav-js about integration](https://github.com/dom111/webdav-js/issues/77) with wsgidav and as a result it'd be great to have the ability to utilise a custom path for the `:dir_browser` argument.

I've made a change, and tested, locally with some success which I'll create a PR for shortly, but thought it best to raise an issue first.

The main reason I'm looking at this is I'd like to make integrating `webdav-js` as easy as possible with as many projects as possible and so providing an example config/setup makes that easy for users and currently the path is hard-coded to use the locally defined assets.

Thanks!

Dom

**Comment by mar10** [comment]
Did you try to set the `mount_path` option?
