### ISSUE TITLE
Per-user read-only / read-write permission?

### ISSUE THREAD

**Issue by fpemud** [mar10/wsgidav#208]
After read doc and some code I found there's no per-user r/w permission support in wsgidav?

**Comment by rootRaider** [comment]
I am actually looking into some `readonly` per user session my self. The `DavProvider` interface does have a `is_readonly` method. I am dynamically updating every request setting this to either `True` or `False` dependent on different things like should the `file` be `readonly` and who the `user` is, etc. It seems to not always override the value though. Maybe the value gets set on `server` startup and set in the `environment`?

**Comment by rootRaider** [comment]
@fpemud @mar10 

I have added this functionality to my `DavProvider` by adding logic per request to `DavProvider.is_readonly`.  I am not sure how you are integrating `WsgiDAV` into your stack @fpemud  i.e. if you are implementing the `WsgiDAV` interfaces or not but it is achievable with little work on a custom `interface`. I think if you need some special user r/w permission support then implement a `DavProvider` and update `is_readonly` appropriately and you should achieve your desired result.
