### ISSUE TITLE
The Python 3.9 doesn't work on Windows7 / Windows Server 2008 R2 / Ealier

### ISSUE THREAD

**Issue by Kylejustknows** [mar10/wsgidav#216]
I know MS dropped support on win7/ win server 2008 etc.  And python 3.9 dropped support on them too.

But wsgidav as a "semi service" program, has been used widely on lots of servers. Sadly, lots of servers are running windows 2008 or earlier, (I see some windows 2000 even).  Many business-critical servers will never get the system upgraded for lots of reasons. I also know many VPS owners still buying and love windows 2008 servers today, as they run well on the budget 512MB Ram VPS machines.

It is unfortunate to find that the latest wsgidav doesn't work on win7/server2008 because of the pythone 3.9.

If a fix or walkaround is available, please let's know.
Thanks!

**Comment by mar10** [comment]
I assume you are talking about the MSI installer only? i never tried it on a legacy system, what error do see then?
I may create patch-release with Python 3.8 for this, ...

The upcoming version v4.0 will probably use the latest Python in builds though, so the workaround will be to stick with WisgDAV 3.x (or run it from a virtual environment).

**Comment by Kylejustknows** [comment]
The way I usually use wsgidav on a server is, use MSI installer on workstation, then copy the result folder to server (make it portable)

In this case, I did tested both methods on the server, comfirmed the latest version failed on winserver2008R2 (python3.9 error).

Thanks for your reply. may my words give you some thoughts though.
