### ISSUE TITLE
Implementation with NextCloud

### ISSUE THREAD

**Issue by LoSunny** [mar10/wsgidav#219]
I'm trying to code the backend and use NextCloud as the frontend. But I didn't realize that they aren't compatible with each other. When I start a test wsgidav server with 
```
wsgidav --host=0.0.0.0 --port=3000 --root=/Users/sunnylo/Downloads/tmp --auth=anonymous
```
I couldn't even upload files, download files from nextcloud, it seems that wsgidav isn't supporting nextcloud's WebDAV protocol?

**Comment by mar10** [comment]
This line starts a local WebDAV server on your client. How is this related to NextCloud, and what errors do you see?
