### ISSUE TITLE
Creating locks for remote MS Word Subdocuments

### ISSUE THREAD

**Issue by philip-mcgrath1** [mar10/wsgidav#223]
Hi,

I am trying to use the MS Word master/sub doc feature to edit multiple docs from within the one document.  This words fine as long as the sub docs are in the same directory as the master doc, however if I try to edit a master doc that contains links to remote subdocs then it never creates locks for these sub docs and Word crashes.

Has any any idea if I can lock remote sub docs ?

**Comment by mar10** [comment]
I am not familiar with the MS Word master/sub docs feature.
Which requests (PROPFIND, LOCK, ...) are sent, and what goes wrong?

**Comment by philip-mcgrath1** [comment]
> I am not familiar with the MS Word master/sub docs feature.
> Which requests (PROPFIND, LOCK, ...) are sent, and what goes wrong?

The Lock request never gets sent for the subdoc so when I try to save changes to the master doc then MS Word crashes because there's no lock for the resource.  However if the subdoc path is something like c:/user/document/subdoc1.docx it works fine but if subdoc is located at http://remoteLocation/subdoc1.docx then it never creates a lock for the resource.
