### ISSUE TITLE
Resumable upload

### ISSUE THREAD

**Issue by dumblob** [mar10/wsgidav#229]
Hi, I'm looking for a WebDAV server which could handle a storage of several terabytes of data (mainly pics & videos). Therefore I need to be absolutely sure the server supports resumable uploads (e.g. after network connection interruption or after smartphone restart etc.). Is it supported **by default** by *wsgidav*? If not, could this be implemented?

And btw. do I need to care myself about SSL certificates or does *wsgidav* have something like (optional) Let's Encrypt support like *caddy* does?

**Comment by dumblob** [comment]
> WsgiDAV supports `Accept-Ranges` headers, so clients should be able to resume downloads.

Ok, downloads are fine. But does the same apply to **up**loads (which this issue is primarily about)?

**Comment by mar10** [comment]
I misread, sorry.
There is no builtin support in WsgiDAV, and it seems [there is no easy or standard way](https://stackoverflow.com/questions/20969331/standard-method-for-http-partial-upload-resume-upload) for this.
