### ISSUE TITLE
in simple_dc is there an option to introduce passwords hashed?

### ISSUE THREAD

**Issue by pvgenuchten** [mar10/wsgidav#232]
having passwords in clear text on config files is not a good convention
would it be interesting to introduce a feature to allow to store the passwords hashed, eg

```
user_mapping:
        "/": true
        "/private": 
            "itsme":
                password: "22215efbafaa0e1b207c271989c369cce662b90233d579c7de8a8a72b9713d5f"
                hash: "SHA256"
```

**Comment by mar10** [comment]
simple_dc is only meant for development or adhoc scenarios.
`wsgidav.dc.pam_dc.PAMDomainController` and `wsgidav.dc.nt_dc.NTDomainController` are better suited in production.
