### ISSUE TITLE
add wfs from map-add-service fails for url's with extra params

### ISSUE THREAD

**Issue by pvgenuchten** [mar10/wsgidav#234]
the add-layer-from-wfs in the add-layer map panel fails because it strips the extra params from the url

extra params is common in for example mapserver; http://example.com/mapserv?map=c:\maps\project.map

the getfeatures request sent is mapserv?request=getfeature....

this happens on 3.12 and 4.0

**Comment by mar10** [comment]
What is " add-layer map panel" and how is this related to WsgiDAV?

**Comment by pvgenuchten** [comment]
Oops sorry, wrong project
