### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by yimisunrise** [mar10/wsgidav#235]
![image](https://user-images.githubusercontent.com/13777332/141609516-c42b37a6-97bf-492f-af71-646ff452cb65.png)

My catalogue contains Chinese.

How do we solve this?

**Comment by mar10** [comment]
What does `wsgidav --version -v` return?
Does it work, when you run it on Python 3?

**Comment by mar10** [comment]
Need more info to analyze

**Comment by yimisunrise** [comment]
> What does `wsgidav --version -v` return? Does it work, when you run it on Python 3?

![image](https://user-images.githubusercontent.com/13777332/145557262-55f038b8-93b0-4a73-8eb5-c3a68b79b0a4.png)

**Comment by yimisunrise** [comment]
> Need more info to analyze

I found the cause of the problem, my directory path contains Chinese.I changed the Chinese directory to English and it works normally.

我发现了导致该问题的原因，我的目录路径中含有中文。我将中文目录修改为英文后可以正常运行了。
