### ISSUE TITLE
Error in sample_wsgidav.yaml?

### ISSUE THREAD

**Issue by Kompressor85** [mar10/wsgidav#242]
Hello!
First I would like to thank you for your nice project! I ran into some problems when updgrading to Version 4, even with a fresh basic configuration. It seems that the problem in my case is "verbose: 0" in the "server_args" of the sample_wsgidav.yaml. I'm not very deep into your code and cheroot, but for me it seems that verbose is no valid argument for cheroot. When I uncomment the server_args everything runs fine.

https://github.com/mar10/wsgidav/blob/b7ce6ce47c7f42b8f7eed0258b89fea4c1951233/sample_wsgidav.yaml#L31

**Comment by mar10** [comment]
Thanks for reporting
