### ISSUE TITLE
range request 'breaks' cors header

### ISSUE THREAD

**Issue by pvgenuchten** [mar10/wsgidav#249]
**Describe the bug**
with cors activated, ajax requests against resources hosted via wsgidav operate fine, but requests with a range header are blocked by the cors policy

**To Reproduce**
- At https://www.test-cors.org, send request to https://files.isric.org/soilgrids/README.md -> CORS ok
- Now add a header `Range: bytes=0-65536` -> CORS failed

**Expected behavior**
CORS header is respected for range requests

**Screenshots, Log-Files, Stacktrace**
Uses latest wsgidav via docker.io/python:3.9.9-slim-bullseye

**Comment by pvgenuchten** [comment]
have to check this in more depth, it may be blocked on our firewall

**Comment by pvgenuchten** [comment]
Confirmed, the Range requests were blocked by our kubernetes ingress, see https://stackoverflow.com/questions/51744536/cors-rules-nginx-ingress-rules how to overwrite. WSGIDAV works as expected! Apologies for disturbance

**Comment by mar10** [comment]
Thanks for the follow up
