### ISSUE TITLE
Windows Mini Redirector Loads and Caches Whole File

### ISSUE THREAD

**Issue by nimamox** [mar10/wsgidav#25]
Hi,
I've written a custom provider for WsgiDAV which fetches the files from some data storage over network and I'm very happy with it. When I use WsgiDAV with almost any client (e.g. OSX Finder), I can see that only the parts requested by client is retrieved. However, if I mount the WsgiDAV resource with Windows native client, that is WebDAV Mini Redirector, and open for example a video file, the whole file is retrieved from the server and only then is handed over to the program, VLC if you may, which as one may argue is nice as seeking different parts of the video is done immediately (as it seems that Windows has cached the whole file), but has the downside of waiting an *unbearable* amount of time for large files to be loaded. I was wondering if this problem is indeed caused by MiniRedir, and if there is any other solution for Windows to mount WebDAV resource without this limitation?

**Comment by mar10** [comment]
(Sorry for the late reply)
I don't think there is much that we can do here: WebDAV (and WsgiDAV) support partial transmissions, the it is up to the client to use it or not.
(Btw. my experience is that Windows MiniRedir is not the best client anyway :-/)
Maybe your application supports to open web day URLs directly?

Closing this for now, unless you or any other have any suggestions...
