### ISSUE TITLE
Support bearer out

### ISSUE THREAD

**Issue by Wissperwind** [mar10/wsgidav#250]
Hi,

I need webdav with bearer auth. We used this token based authentication system. Would you like to add this to your library?
Maybe it is possible to provide a method to check the tokens to your system so your system can accept bearer auth.

**Comment by Wissperwind** [comment]
No human answer?

**Comment by mar10** [comment]
I don't have capacity to setup  this scenario an implement/test it, sorry .
However if you propose a PR I will look onto it.
