### ISSUE TITLE
support HTTP Redirect in server and provider

### ISSUE THREAD

**Issue by karma-sun** [mar10/wsgidav#253]
**Describe the bug**
sometimes we need to provide a resource at external URL and let client request that URL directly,but send_resource method of server do not provide support for HTTP Redirect

**Comment by mar10** [comment]
Thank you for contributing! :+1:

In order to process your issue, we need some more information, explanation what already was tried and/or concrete data.

**Comment by karma-sun** [comment]
I tried to extend DAVNonCollection:
`class MyDAVNonCollection(DAVNonCollection):
...omit some code

    def get_content(self):
        # here I have a URL point to file in external server and want client to request it directly,but get_content() need return a file object,it is not good for me to open the file URL and return data, because the file is very large(may be 1GB or more)
`

**Comment by Wamy-Dev** [comment]
I've achieved this here:

https://github.com/Wamy-Dev/TorBox-webdav/commit/fa8749a0d7e1a284fc1018029e711948cd592494
