### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll missing

### ISSUE THREAD

**Issue by andrewchenshx** [mar10/wsgidav#257]
**Describe the bug**
install with [MSI installer](https://github.com/mar10/wsgidav/releases), invoke the wsgidav from commandline, it prompts 
api-ms-win-core-path-l1-1-0.dll missing
**To Reproduce**
1. download [WsgiDAV-4.0.1.0-win64.msi](https://github.com/mar10/wsgidav/releases/download/v4.0.1/WsgiDAV-4.0.1.0-win64.msi)
2. Click and install
3. run wsgidav from the command line

**Environment:**
```
windows 7 x64,
```

**Additional context**
searching api-ms-win-core-path-l1-1-0.dll on my pc with everything.exe results in no file.

**Comment by mar10** [comment]
I assume this is specific to the legacy windows version.
[Windows 7 support ended on January 14, 2020](https://support.microsoft.com/en-au/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962) and I don't have plans to support this any more.
Please let us know if it happens an recent platforms as well, thanks.

**Comment by andrewchenshx** [comment]
it works on my win10 x64 laptop. thanks.
