### ISSUE TITLE
HTTP Range outputs wrong responses

### ISSUE THREAD

**Issue by adriancretu** [mar10/wsgidav#26]
Current design does not allow returning resource content starting from a particular Range offset.

This makes it impossible to use it as a layer over HTTP resources (think Dropbox, Drive, any other cloud storage), because the library wants a "file-like" object to be returned from the getContent() method.
A "file-like" object unfortunately is not seekable when it comes to a network stream, and this little detail is not documented anywhere.

Unfortunately it then uses that to call "seek()" on it when it needs a particular range requested from the client, which results in two possible scenarios, both bad:
1. If we return "True" for "supportRanges", server crashes because seeking is not possible in a network stream.
2. If we return "False" (default), then the client always receives data starting at the beginning of the file!!! This results in later beautiful exceptions like "The remote client closed the connection" and things like that, because the client is not receiving correct data.
Actually, the server enters a never-ending loop of exceptions right after a client closes a connection unexpectedly for the first time.

Is there a way to make this work? e.g. add range start/end parameter to the getContent method? so the resource will return a fresh, correct, raw stream handle that will read data from the specified position?

**Comment by mar10** [comment]
A first idea could be to have an additional method with default implementation, that you could override
```py
def getContentAt(self, seek):
    res = self.getContent()
    if seek > 0:
        res.seek(0)
    return 
```
Then, request_server._sendResource could call this instead:
```py
fileobj = res.getContentAt(rangestart)
# (omit seeking here, but read from fileobj)
...
```

Can you provide test cases, before we add changes?

Btw.
> If we return "False" (default), then the client always receives data starting at the beginning of the file!!! This results in later beautiful exceptions like "The remote client closed the connection" and things like that, because the client is not receiving correct data.

As I understand it, this is complaint with WebDAV: if a server chooses to not support ranges, it will not add the `Allow-Ranges` header, and a client must handle that.

**Comment by adriancretu** [comment]
Hey there.
I followed your suggestion and actually overridden the getContent() method, adding two arguments (range_start and range_end), creating a correct HTTP request for the content. Now the client (XBMC on Android) can play video files stored in Google Drive through a WebDAV proxy.

But seeking is not working as expected. When I try to seek to the middle / end of a movie, it seems as if the same stream is being used to read-ahead at maximum download speed, until the new position is reached. I will investigate this to see if getContent is called again or not. The idea is that the stream is seek able and the server should get hit with a fresh request, unless there is some headers being sent which would disable this?

Regarding the "Allow-Ranges" header: why is data still returned from the beginning of the file if the server does not support ranges? Also, it is very easy in any case to crash the server by simply opening a connection to it and just killing it before all the data was read by the client (I had to comment out ignoring the errors 10053 and 10054, they cause almost infinite exception loop. They should also throw out, to stop the server trying to send data to a dead socket). In my case, stopping a video before it finishes playing will always get to this situation, so it's a common scenario.

**Comment by mar10** [comment]
It's in the spec. If the server indicates that it does not accept ranges, the client should not request that in the first place. If it still does, the server is free to ignore the range header and send everything.
See here: http://stackoverflow.com/questions/6204283/http-how-should-i-respond-to-range-bytes-when-range-is-unsupported/6204397#6204397

I assume you created a custom provider that delegates GET requests to Google Drive? 
Of course, a TCP stream is not seekable, but you could you simply pass each range-requests on to the target Google server, so the seeking is done there?

**Comment by adriancretu** [comment]
The HTTP socket exceptions were solved by running the provider under the production "wsgidav" binary, they only appeared when running in development mode (just as they do when using any wsgi framework), so it's not a bug.

In the end, I didn't touch at all the source code of WsgiDAV. I worked-around the seek() call by just returning a wrapper "file-like" object which created the proxied HTTP range request call.

But there is just one down-side to this, which would be awesome if it can be addressed: because we only receive the "range_start" position, the HTTP GET call done by the provider will actually request an indefinite amount of data, instead of a fixed length. While not an actual bug (everything works perfectly), this kind of breaks connection pooling when seeking through a file (because the previous connection has to be force-closed as it has not finished reading the entire data that the server keeps pushing down).

How much of a trouble would be to add a second argument to seek, considering how other providers work? The line in question would be [this one](https://github.com/mar10/wsgidav/blob/master/wsgidav/request_server.py#L1475).

**Comment by mar10** [comment]
I probably did not fully understand everything completely, but changing the signature of *filelike.seek(offset[, whence])* seems not to be a good idea (https://docs.python.org/2/library/io.html#io.IOBase.seek).

Maybe you can fork and start a branch that adds some use cases, tests, and maybe finally have a pull request to discuss? (Going to close this issue for now, but we can re-open later)
