### ISSUE TITLE
Case-Sensitivity issue on MOVE/COPY actions through Windows DAV

### ISSUE THREAD

**Issue by afrench-webworks** [mar10/wsgidav#260]
**Describe the bug**
When I try to move a file via Windows Explorer DAV (a rename, cut/paste, etc.), my request is rejected and I get a prompt stating "Cannot read file or disk".

**To Reproduce**
1. Connect to WsgiDAV service via Windows Explorer
2. Navigate to folder
3. Try to rename a file

**Expected behavior**
I expected to be able to rename and move files and directories via Windows Explorer DAV.

**Environment:**
```
wsgidav version 4.0.1
```

Using `cheroot`, Windows File Explorer

**Additional context**
I was able to fix this issue by modifying the logic in `request_server.py`. By lowercasing `dest_netloc` in the check, it goes through without failing. Seems like it might be important because the strings they  are being compared against actually are lowercased when assigned.

`request_server.py`, method `_copy_or_move`

From:
```python
        if dest_scheme and dest_scheme not in (url_scheme, fwd_scheme):
            self._fail(
                HTTP_BAD_GATEWAY,
                "Source and destination must have the same scheme.\n"
                "If you are running behind a reverse proxy, you may have to "
                "rewrite the 'Destination' haeader.\n"
                "(See https://github.com/mar10/wsgidav/issues/183)",
            )
        elif dest_netloc and dest_netloc not in (url_host, fwd_host):
            # TODO: this should consider environ["SERVER_PORT"] also
            self._fail(
                HTTP_BAD_GATEWAY, "Source and destination must have the same host name."
            )
```

To:
```python
        if dest_scheme and dest_scheme.lower() not in (url_scheme, fwd_scheme):
            self._fail(
                HTTP_BAD_GATEWAY,
                "Source and destination must have the same scheme.\n"
                "If you are running behind a reverse proxy, you may have to "
                "rewrite the 'Destination' haeader.\n"
                "(See https://github.com/mar10/wsgidav/issues/183)",
            )
        elif dest_netloc and dest_netloc.lower() not in (url_host, fwd_host):
            # TODO: this should consider environ["SERVER_PORT"] also
            self._fail(
                HTTP_BAD_GATEWAY, "Source and destination must have the same host name."
            )
```

**Comment by mar10** [comment]
Please have a look at my commit (slightly different): does it solve the problem?
