### ISSUE TITLE
use my own API to upload file rather than `begin_write` and `end_write`

### ISSUE THREAD

**Issue by HengyueLi** [mar10/wsgidav#262]
For my case, I already have an API, an Python function `api_upload(path)`, to implement write. For example, a file with local path `filepath="/home/foo/1.png"`, can be "writen" directly by  a function call `api_upload(path=filepath)`. That is all. How can I simplify `begin_write` and `end_write`?

**Comment by mar10** [comment]
Have a look at [`FileLikeQueue`](https://github.com/mar10/wsgidav/blob/master/wsgidav/stream_tools.py)

**Comment by mar10** [comment]
See also #253
