### ISSUE TITLE
wsgidav shows absolute path in web interface

### ISSUE THREAD

**Issue by ElFishi** [mar10/wsgidav#268]
I have wsgidav running on port 8080 behind a nginx reverse proxy. 
The relevant part of the config goes like this
```
        location /drive/ { # wsgidav - mind the trailing slash

                proxy_pass http://localhost:8080/; # - mind the trailing slash
                proxy_http_version 1.1;
                proxy_set_header HOST $host;
                #proxy_set_header Connection "upgrade";
                proxy_set_header X-NginX-Proxy true;
                proxy_buffering off;
                client_max_body_size 0;
                proxy_request_buffering off;
        }
```
Adding a network drive from windows works just fine. 

However, if I look at the server by entering the URL in a web browser, I get the top level directory with links to the lower level directories with absolute pathes. 
This means the links break behind a reverse proxy. 

Not a big issue, but it would be nicer to serve the links with relative pathes so they still work with a reverse proxy.  
**Environment:**
```
WsgiDAV/4.0.3-a1 Python/3.9.2(64 bit) Linux-5.15.61-v8+-aarch64-with-glibc2.31
Python from: /usr/bin/python3
```
Thx

**Comment by ElFishi** [comment]
I have a workaround: 
my reverse proxy lives at myserver.com/drive/ and if I serve the webdav directory at /drive, too, the links for the subdirectories work. 
To salvage the css and the logo at src="/:dir_browser/logo.png" I added 
`location /:dir_browser { proxy_pass http://127.0.0.1:8080/:dir_browser; }`
to the nginx config.

I also updated the config to say 
```
map $http_destination $driveDestination { # otherwise MOVE results in a 502 Bad Gateway
        default $http_destination;
        "~*^https://drneuhold.de/drive/(.+)" /$1;
}
```
outside the server block and 
```
        ## Begin - webdav
        location /drive/ { # wsgidav - trailing slash means it will be added

#               proxy_pass http://127.0.0.1:8080/; # - trailing slash means location will be dropped
                proxy_pass http://127.0.0.1:8080; # - serve webdav at /drive

                # https://github.com/mar10/wsgidav/issues/183
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_buffering off;
                client_max_body_size 0;
                proxy_request_buffering off;

                proxy_set_header Destination $driveDestination; # result of map command above
        }
        location /:dir_browser {
                proxy_pass         http://127.0.0.1:8080/:dir_browser;
        }
        ## End - webdav
```
inside the server block.

Still, less workarounds would be nice.

**Comment by mar10** [comment]
Thanks for reporting!
Using relative HREF's should be easy. Did you encounter any other problems when running behinfd a proxy except for dir dir-browser URLs?

**Comment by ElFishi** [comment]
No, with the workarounds it looks OK. 

I tweaked the dir-browser template to include 
```
<script type="text/javascript">
["/:dir_browser/style-min.css","/:dir_browser/webdav-min.js"].forEach((function(e,s){/css$/.test(e)?((s=document.createElement("link")).href=e,s.rel="stylesheet"):(s=document.createElement("script")).src=e,document.head.appendChild(s)}));

window.addEventListener('DOMContentLoaded', function () { document.body.innerHTML='';  });

</script>
```
where I nicked the files and the js line from https://github.com/dom111/webdav-js.

Having said that, I'm in the market for even nicer dir browsers : )

**Comment by kekkodance** [comment]
getting this issue too.

**Comment by ElFishi** [comment]
:dir_browser still comes in absolute href or src, respectively.
```
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="generator" content="WsgiDAV/4.0.3-a1">
  <title>WsgiDAV - Index of / </title>
  <link rel="shortcut icon" href="/:dir_browser/favicon.ico">
  <link rel="stylesheet" href="/:dir_browser/style.css" />
  <script defer src="/:dir_browser/script.js"></script>
  <style type="text/css"> A {behavior: url(#default#AnchorClick);} </style>
</head>

<body onload="onLoad()">

  <h1>
    <img class="logo" alt="WsgiDAV" title="WsgiDAV" src="/:dir_browser/logo.png">
```
The directory links are relative and work on the first level.
However, one directory down  ".." does not lead to the top level but to the server URL. 

I.e. my WebDAV is served at myserver.com/drive.
On top level I have a directory called "boot": I click on it and get to /drive/boot and have the contents alright.
If I want to go up again and click "..", I get to myserver.com, i.e. out of webdav.
If I want to open a file on this level , e.g. config.txt, I get /drive/config.txt instead of /drive/boot/config.txt
  
My nginx config goes 
```
map $http_destination $driveDestination { # otherwise MOVE results in a 502 Bad Gateway
        default $http_destination;
        "~*^https://myserver.com/drive/(.+)" /$1;
}
```
in the html section and
```
    location /drive/ { # wsgidav - trailing slash means it will be added

            proxy_pass http://127.0.0.1:8080/; # - trailing slash means location will be dropped
    #               proxy_pass http://127.0.0.1:8080; # - serve webdav at /drive

            # https://github.com/mar10/wsgidav/issues/183
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_buffering off;
            client_max_body_size 0;
            proxy_request_buffering off;

            proxy_set_header Destination $driveDestination; # result of map command above
    }
```
in the server section.
