### ISSUE TITLE
Issues with a file if it's saved from application

### ISSUE THREAD

**Issue by rusaym** [mar10/wsgidav#271]
**Describe the bug**
If a file was created from the application, than you can't delete it. Tested on MS Word 2016.

https://user-images.githubusercontent.com/17137916/199465671-f908d344-12d4-40b2-8778-503fa992b135.mp4

**Environment:**
```
WsgiDAV/4.0.1 Python/3.10.6(64 bit) Linux-5.15.0-52-generic-x86_64-with-glibc2.35
```

**Comment by rusaym** [comment]
After waiting some time you can delete the file

**Comment by rusaym** [comment]
Do you have any suggestion to fix this bugs at least temporary?
1. I noticed that deletion issues occur with office documents, I can guess it's because of integration with office document formats. Can I somehow disable all office integrations?
2. Refreshing issue occur also with webdav client library  ( I tried  https://www.npmjs.com/package/webdav), when I create file or folder I have to refresh destination folder from file explorer to see created file/folder. Maybe there is any way to manually refresh destination folder from Provider implementation?

Thanks.

**Comment by mar10** [comment]
I don't have access to MS Office most of the time, but I am not yet convinced that we have a bug.
Can you please provide a log file of the request sequence during the issue?
(Note that WebDAV does not support any API to actively push changes to clients, so if MS Word saves a file, that you opened from MS File Explorer, it is up to the Explorer to refresh the view.)
