### ISSUE TITLE
The request url of the file in the subdirectory is incorrect.

### ISSUE THREAD

**Issue by feiniks** [mar10/wsgidav#274]
**Describe the bug**
Hello, after I use the latest master branch to deploy webdav, if I access a file in a secondary directory through a browser, such as `dir/subdir/test.md`, the corresponding request url of the file will become `http:// 127.0.0.1:8080/test.md`, this will return a 404 error, the correct url should be `http://127.0.0.1:8080/dir/subdir/test.md`. This should be related to this commit `b96f07f3f28b2d99c9e86c9edef2cacaced24de8`, can you confirm the issue.
Thanks.

**Expected behavior**
Files in subdirectories can be accessed through a browser.

**Comment by mar10** [comment]
Could you try with the latest commits?

**Comment by feiniks** [comment]
> 

Hello, the latest commit works fine.
Thanks.

**Comment by mar10** [comment]
Thanks
