### ISSUE TITLE
logger in WsgiDAVApp(webdavConfig) prints only the second time

### ISSUE THREAD

**Issue by Wissperwind** [mar10/wsgidav#279]
I create two objects using: 
WsgiDAVApp(webdavConfig)

In wsgidav_app.py is a _logger. In theory it prints seome things every time I call the constructor like above. But the strange thing is that the logger prints only the second time something.

So for a long time I created only one WsgiDAVApp object in my code. No prints, and I don't missed some prints.
But today I created a second Object which is verry similar. Is has only a different folder to provide webdav access to. And the second time I run this constructor in the code I get some prints. And I ask why? What do those prints mean?

```
24.01 10:37:53 App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
24.01 10:37:53 WsgiDAV/4.1.0 Python/3.10.4 Windows-10-10.0.19043-SP0
24.01 10:37:53 Lock manager:      LockManager(LockStorageDict)
24.01 10:37:53 Property manager:  None
24.01 10:37:53 Domain controller: None
24.01 10:37:53 Registered DAV providers by route:
24.01 10:37:53   - '/:dir_browser': FilesystemProvider for path 'C:\...\python310environment\lib\site-packages\wsgidav\dir_browser\htdocs' (Read-Only) (custom auth)
24.01 10:37:53   - '/': FilesystemProvider for path 'C:\...\data\ForeignJobBasePath' (Read-Write) (custom auth)
```

Is there a way to not get these prints both times?

**Comment by mar10** [comment]
Thank you for contributing! :+1:

In order to process your issue, we need some more information, explanation what already was tried and/or concrete data.

A debuggable example may be helpful.

(You could also give [Stackoverflow](https://stackoverflow.com/questions/tagged/wsgidav) a try.)

Thank you,
~Martin

**Comment by Wissperwind** [comment]
I don't need two objects anymore.
