### ISSUE TITLE
Informational: wsgidav is now on conda-forge

### ISSUE THREAD

**Issue by timj** [mar10/wsgidav#286]
This is not a bug report. I needed to use wsgidav in conda-forge so I have added a feedstock and `conda install wsgidav cheroot` should now work. Please let me know if you want to be added to the feedstock as a maintainer.

Located at: https://github.com/conda-forge/wsgidav-feedstock

**Comment by mar10** [comment]
Great work, thank you! 
(No need to add me as a maintainer.)
