### ISSUE TITLE
Add environ arg to _locToFilePath for per-user chrooting?

### ISSUE THREAD

**Issue by jonasbardino** [mar10/wsgidav#29]
Hi Martin

We run a setup with a custom FilesystemProvider where we want to limit users to their individual home sub-directory inside rootFolderPath. I thought we'd already managed that with the existing wsgidav code, but it turns out we ran into a nasty race when trying to override the lookup function dynamically.

Would it be acceptable for you to change the _locToFilePath method to take not only the path but additionally an environ argument (in symmetry with getResourceInst)?
In that way we only need to override that method once and for all to use the username auth header for the chroot-mapping.

It requires a few call changes throughout fs_dav_provider.py but I can provide a pull request if that's any help?

Cheers, Jonas

**Comment by mar10** [comment]
I guess that would be ok, except that it might break existing code that inherits from FilesystemProvider or otherwise calls _locToFilePath().
So the additional parameter should be optional and default to None?
A PR would be cool.

**Comment by jonasbardino** [comment]
Sounds good, I've made a PR with that in mind now.
