### ISSUE TITLE
Problem to open excel and power point files

### ISSUE THREAD

**Issue by jonasviera** [mar10/wsgidav#297]
**Describe the problem**
I'm working on a project that is essentially a Word file (docx) management system. However, I'm now starting to implement the use of PowerPoint and Excel files. Word files have always worked very well, allowing for file opening, editing, and saving without any issues.

However, when using files (.xlsx and .pptx), I'm encountering the following problems:
Excel file: The issue arises when I try to open an Excel file and, when attempting to save it for the first time, it asks me to discard my changes first and only then allows me to save it.
PowerPoint file: When opened and I try to save a change, it keeps prompting me to save again indefinitely.

**Expected behavior**
Open, edit and save without any issues.

wsgidav --version -v
WsgiDAV/3.1.1 Python/3.8.16(64 bit) Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
Python from: /home/jonasvieira/.asdf/installs/python/3.8.16/bin/python3.8

Any ideia for that? Thanks

**Comment by mar10** [comment]
Can you try with the latest release?
If it still fails, please provide log files in --verbose mode
Thx
