### ISSUE TITLE
Exception in destructor

### ISSUE THREAD

**Issue by mrjcrunchjob** [mar10/wsgidav#31]
I've bumped into this exception:
Exception TypeError: "'NoneType' object is not callable" in <bound method PropertyManager._del_ of PropertyManager> ignored
Maybe the problem is that destructor of PropertyManager instance calls global function(currentThread) which has been already destroyed by garbage collector(wsgidav/rw_lock.py line 128)?

**Comment by mar10** [comment]
Thanks. Can you provide some details how this could be reproduced?
