### ISSUE TITLE
Chunked transfer from some webdav clients are failing

### ISSUE THREAD

**Issue by aleqx** [mar10/wsgidav#312]
EDIT: Please ignore this. Seafile is using WsgiDAV 4.1.0 which is too old, and I just noticed you fixed this very issue in 4.3.0 here https://github.com/mar10/wsgidav/commit/dd3e53a5c57b03c19d1d240fbe949b8f75dd6850

~~I reported it first at the Seafile project, which uses WsgiDAV, but it is in fact an issue with WsgiDAV (well, sort of): https://github.com/haiwen/seafile/issues/2723#issuecomment-1905266353 (and the message above in the same issue, namely https://github.com/haiwen/seafile/issues/2723#issuecomment-1905226877)~~

~~MIght you be agreeable to the idea of making WsgiDAV more flexible, like Apache is, to accommodate these?~~

**Comment by mar10** [comment]
Thanks for reporting anyway!
