### ISSUE TITLE
Start failed when using pipx install wsgidav cheroot

### ISSUE THREAD

**Issue by hasayakey** [mar10/wsgidav#313]
**Describe the bug**
Start failed when using pipx install wsgidav cheroot

**To Reproduce**
1. brew install pipx
2. pipx install wsgidav cheroot
3. wsgidav --host=0.0.0.0 --port=8080 --root=$(pwd) --auth=anonymous

**Expected behavior**
no error when starting

**Screenshots, Log-Files, Stacktrace**
```
Running without configuration file.
10:39:03.822 - WARNING : App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
10:39:03.828 - INFO    : WsgiDAV/4.3.0 Python/3.12.1 macOS-14.3-arm64-arm-64bit
10:39:03.828 - INFO    : Lock manager:      LockManager(LockStorageDict)
10:39:03.828 - INFO    : Property manager:  None
10:39:03.828 - INFO    : Domain controller: SimpleDomainController()
10:39:03.828 - INFO    : Registered DAV providers by route:
10:39:03.828 - INFO    :   - '/:dir_browser': FilesystemProvider for path '/Users/edy/Library/Application Support/pipx/venvs/wsgidav/lib/python3.12/site-packages/wsgidav/dir_browser/htdocs' (Read-Only) (anonymous)
10:39:03.828 - INFO    :   - '/': FilesystemProvider for path '/Users/edy' (Read-Write) (anonymous)
10:39:03.828 - WARNING : Basic authentication is enabled: It is highly recommended to enable SSL.
10:39:03.828 - WARNING : Share '/' will allow anonymous write access.
10:39:03.828 - WARNING : Share '/:dir_browser' will allow anonymous write access.
10:39:03.828 - WARNING : Could not import lxml: using xml instead (up to 10% slower). Consider `pip install lxml`(see https://pypi.python.org/pypi/lxml).
10:39:03.829 - ERROR   : Could not import Cheroot (https://cheroot.cherrypy.dev/).
Traceback (most recent call last):
  File "/Users/edy/Library/Application Support/pipx/venvs/wsgidav/lib/python3.12/site-packages/wsgidav/server/server_cli.py", line 433, in _run_cheroot
    from cheroot import server, wsgi
ModuleNotFoundError: No module named 'cheroot'
10:39:03.829 - ERROR   : Try `pip install cheroot`.
```
If applicable, add a log file (consider `--verbose`).

**Environment:**
```
WsgiDAV/4.3.0 Python/3.12.1(64 bit) macOS-14.3-arm64-arm-64bit
Python from: /Users/edy/Library/Application Support/pipx/venvs/wsgidav/bin/python
```

Which WSGI server was used (cheroot, ext-wsgiutils, gevent, gunicorn, paste, uvicorn, wsgiref, ...)?

Which WebDAV client was used (MS File Explorer, MS Office, macOS Finder, WinSCP, Windows, file mapping, ...)?

**Additional context**

**Comment by mar10** [comment]
As the error message says:

> 10:39:03.829 - ERROR   : Try `pip install cheroot`.

You must install a server separately. See also the [--server](https://wsgidav.readthedocs.io/en/latest/user_guide_cli.html#cli-options) option

**Comment by hasayakey** [comment]
> As the error message says:
> 
> > 10:39:03.829 - ERROR   : Try `pip install cheroot`.
> 
> You must install a server separately. See also the [--server](https://wsgidav.readthedocs.io/en/latest/user_guide_cli.html#cli-options) option

Thanks for reply ！
I figured out the difference between pipx and pip.
`pipx install wsgidav --pip-args cheroot` works fine !
