### ISSUE TITLE
Digest authentication rejected due to invalid header

### ISSUE THREAD

**Issue by adriancretu** [mar10/wsgidav#32]
The header returned by the server when the Digest protocol is used is not formatted correctly.
VLC rejects the authentication header due to invalid algorithm "MD5", when it should be MD5.
Please see  [RFC2617](https://tools.ietf.org/html/rfc2617#section-3.2.1)

Note that I first thought this is a VLC issue, until they proved me wrong in reading the spec. The algorithm name should not be quoted. Actual quotes are escaped in the spec as <">.

Current format of authentication header:
    Digest realm="/", nonce="some_nonce", algorithm="MD5", qop="auth"

Should be:
   Digest realm="/", nonce="some_nonce", algorithm=MD5, qop="auth"

**Comment by mar10** [comment]
Thank you, sir.
