### ISSUE TITLE
Docker Seafile 11 Seafdav (Webdav using wsgidav in version 11) upload issue: file is to big

### ISSUE THREAD

**Issue by nobe80** [mar10/wsgidav#324]
Hi,

i have faced an issue with Seafile webdav (Seafdav, that uses wsgidav) when i use Seafile version 11 after upgrade.
The issue is the follow:

In Windows file explorer i have successful a Webdav drive over https to the Seafile server. So seafdav is enabled, we can see all folders. When i upload some files like pdf or simple text files i get an error “…file is to big…” and i have 0 Bytes files in the folder.

When i downgrade again to Seafile Version 10 (without wsgidav) no problems at all. Everything works fine then.
We use Sefafile docker community.

Does anyone have a hint what could be the reason?

**Comment by mar10** [comment]
Hi,
can you reproduce it with a standalone version of WsgiDAV?
I don't know how Seafdav uses WsgiDAV, so I it might be better to report the issue there otherwise.
