### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by mar10** [mar10/wsgidav#4]
See also pep3333
http://www.python.org/dev/peps/pep-3333/#a-note-on-string-types

**Comment by mar10** [comment]
Started [py3 branch](https://github.com/mar10/wsgidav/tree/py3)

**Comment by jcea** [comment]
What is the status of Python 3 support? Thanks!.

**Comment by mar10** [comment]
Alpha - I have seen the litmus suite passing, but the test framework and add-ons still need work.

**Comment by cryptocxeq** [comment]
Any update on this? Sorry.

**Comment by mar10** [comment]
It is currently not on my top priority list, primarily because I don't have a python 3 project that uses it.
But you could push it by contributing: checkout the [Py3 branch](https://github.com/mar10/wsgidav/tree/py3), test it, and provide feedback. I don't think that it is far from release status.

**Comment by wallacms** [comment]
I'm also interested in using WsgiDAV with python 3 and I'm trying to get the tests running (using the py3 branch).  The main thing I'm running into is problems with tox - the setup.py is referencing files in the source (for example wsgidav/_version.py) but these files don't seem to be included in the zip file that is created by tox.  I don't really have any experience with these tools so I'm hoping you can point me in the right direction.  Below is the exact error I'm getting:

Processing ./.tox/dist/WsgiDAV-3.0.0rc1.dev20160818.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/8z/0l0ht22n5lb2dv6lx9dmfwx80000gn/T/pip-z_qvh4ns-build/setup.py", line 66, in <module>
        exec(open("wsgidav/_version.py").read(), g_dict)
    FileNotFoundError: [Errno 2] No such file or directory: 'wsgidav/_version.py'
    Could not import cx_Freeze; 'build' and 'bdist' commands will not be available.
    See https://pypi.python.org/pypi/cx_Freeze

**Comment by pokoli** [comment]
@wallacms  could you test PR #33 ? This fixes the issue for me.

Test are not passing, but now they can be run, so its a first step.

**Comment by tomviner** [comment]
@wallacms it's failing because the `packages` arg has been commented out in the [`setup.py` in this branch](https://github.com/tomviner/wsgidav/blob/py3/setup.py#L139).

I'm not sure why that was commented out, I'd suggest putting it back in.

**Comment by mar10** [comment]
Cool to see there is some community activity going on!!

By chance I happened to push some pending commits to Py3 just shortly before Sergi's PR #33 .
Sorry for the inconvenience... 
Even worse, my main laptop broke down minutes later.
Anyway I hope this get's some momentum now, and we can get Py3 to run over the next weeks.

The tox/py.test framework is important, but if some of you have Python 3 projects running, it would also be helpful to test in such a real world scenario.

**Comment by cryptocxeq** [comment]
Hi, unfortunately my coding knowledge is pretty basic and I'm not confident in my own ability to test or commit. However, I thought it might be helpful to tell you that I am using wsgidav as a part of the project pyspider found here: https://github.com/binux/pyspider/

This project seems fairly popular so if you are looking for a real world use case maybe this can help.

**Comment by mar10** [comment]
Tests run (but don't pass yet) on Py27, py33, py34, and py35.
I also added https://github.com/mar10/wsgidav/blob/py3/CONTRIBUTING.md of the set up description.

New findings should go into separate issues with the Py3 tag now.

**Comment by pokoli** [comment]
@mar10 I see that test are passing on py3, are we ready for merging? Which work is still pending?

**Comment by mar10** [comment]
My next steps are

* [ ] Merge branch 'issue_28' to master
* [ ] Test master
* [ ] Release v1.3
* [ ] Create branch 'maintain_1.x'
* [ ] Merge master to Py3
* [ ] Test Py3
* [ ] Merge Py3 to master
* [ ] Test master
* [ ] Release v2.0.0rc1

Pending work in Py3 branch (maybe you can help here):

* [ ] Most importantly: test in *real* projects
* [ ] SSL not working (run `$ wsgidav` from project root folder)
* [ ] We might add some tests (Currently 49% coverage)
* [ ] We could add some benchmarks; would be interesting to compare v1.3 to 2.0 and also 2.0 running on Py2 vs. Py3

**Comment by mar10** [comment]
A 2.0.0 beta ('nightly build') is now available on PyPI, ready for testing.
Please report findings as new issues...

**Comment by wallacms** [comment]
I’ve just started running the latest nightly build from PyPI and it’s working for me under Python3.5.  Thanks for the help!

FWIW, my application is very simple right now, I’m using WSGIDav to do syncing for OmniFocus.  The clients are OmniFocus for OS X and OmniFocus for iOS.

-Matt
