### ISSUE TITLE
CalDAV-support

### ISSUE THREAD

**Issue by DrAzraelTod** [mar10/wsgidav#5]
> #### This issue is currently deferred
> Due to low priority and current lack of resources, this issue was tentatively put aside.
> See also [info about deferred issues](https://github.com/mar10/fancytree/wiki/DeferredIssues).

as mentioned on the old [google-code-ticket][1], CalDav-Support would be great (even though it's probably something that won't really happen)

    **What new or enhanced feature are you proposing?**
    Extending wsgidav with caldav

    **What goal would this enhancement help you achieve?**
    Allowing enhanced calendar support for a collaborative site i'm working on

[1]: https://code.google.com/p/wsgidav/issues/detail?id=42

**Comment by mar10** [comment]
Due to low priority and current lack of resources, this issue was tentatively put aside.
See also [info about deferred issues](https://github.com/mar10/fancytree/wiki/DeferredIssues).
