### ISSUE TITLE
pip install wsgidav error

### ISSUE THREAD

**Issue by dzhyw** [mar10/wsgidav#50]
CentOS release 6.7 x86_64
python2.7
WsgiDAV-2.0.1 install error: 

sh: /usr/bin/ldd: /usr/bin/bash: bad interpreter: 没有那个文件或目录
    copying doc/logo.ico -> build/exe.linux-x86_64-2.7/logo.ico
    error: [Errno 2] No such file or directory: 'doc/logo.ico'

please fix it,thanks

**Comment by mar10** [comment]
Please provide more information: what exactly did you enter, and what is output to the console. Are you using a virtualenv?

**Comment by mar10** [comment]
Seems to work here (ubuntu 14.04 LTS, 64bit)
```
(py27)martin@mubuntu:~/prj/git$ pip install wsgidav
Collecting wsgidav
  Using cached WsgiDAV-2.0.1.zip
Collecting defusedxml (from wsgidav)
/home/martin/.virtualenvs/py27/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/martin/.virtualenvs/py27/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached defusedxml-0.4.1.tar.gz
Installing collected packages: defusedxml, wsgidav
  Running setup.py install for defusedxml ... done
  Running setup.py install for wsgidav ... done
Successfully installed defusedxml-0.4.1 wsgidav-2.0.1
(py27)martin@mubuntu:~/prj/git$ wsgidav -V
2.0.1
(py27)martin@mubuntu:~/prj/git$ 
```
Let me know if you can provide additional information

**Comment by dzhyw** [comment]
hi,mar10:
 first,Thanks for your reply。
 I no using a virtualenv, it's my operating record;
[root@localhost ~]# pip install --egg wsgidav
Collecting wsgidav
  Downloading http://mirrors.aliyun.com/pypi/packages/c7/dc/83f91b47177bbc3c287e311063f5d410c79aecddcb303ed017b47cadd59e/WsgiDAV-2.0.1.zip (138kB)
    100% |████████████████████████████████| 143kB 1.4MB/s 
Requirement already satisfied (use --upgrade to upgrade): defusedxml in /usr/local/lib/python2.7/site-packages (from wsgidav)
Installing collected packages: wsgidav
  Running setup.py install for wsgidav ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z2yvLQ/wsgidav/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MNXqFi-record/install-record.txt --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/wsgidav
    copying wsgidav/debug_filter.py -> build/lib/wsgidav
    copying wsgidav/util.py -> build/lib/wsgidav
    copying wsgidav/_version.py -> build/lib/wsgidav
    copying wsgidav/__init__.py -> build/lib/wsgidav
    copying wsgidav/lock_manager.py -> build/lib/wsgidav
    copying wsgidav/lock_storage.py -> build/lib/wsgidav
    copying wsgidav/dav_provider.py -> build/lib/wsgidav
    copying wsgidav/domain_controller.py -> build/lib/wsgidav
    copying wsgidav/http_authenticator.py -> build/lib/wsgidav
    copying wsgidav/dav_error.py -> build/lib/wsgidav
    copying wsgidav/compat.py -> build/lib/wsgidav
    copying wsgidav/wsgidav_app.py -> build/lib/wsgidav
    copying wsgidav/dir_browser.py -> build/lib/wsgidav
    copying wsgidav/error_printer.py -> build/lib/wsgidav
    copying wsgidav/xml_tools.py -> build/lib/wsgidav
    copying wsgidav/fs_dav_provider.py -> build/lib/wsgidav
    copying wsgidav/middleware.py -> build/lib/wsgidav
    copying wsgidav/property_manager.py -> build/lib/wsgidav
    copying wsgidav/request_server.py -> build/lib/wsgidav
    copying wsgidav/rw_lock.py -> build/lib/wsgidav
    copying wsgidav/request_resolver.py -> build/lib/wsgidav
    creating build/lib/wsgidav/addons
    copying wsgidav/addons/hg_dav_provider.py -> build/lib/wsgidav/addons
    copying wsgidav/addons/__init__.py -> build/lib/wsgidav/addons
    copying wsgidav/addons/mongo_property_manager.py -> build/lib/wsgidav/addons
    copying wsgidav/addons/nt_domain_controller.py -> build/lib/wsgidav/addons
    copying wsgidav/addons/couch_property_manager.py -> build/lib/wsgidav/addons
    copying wsgidav/addons/mysql_dav_provider.py -> build/lib/wsgidav/addons
    creating build/lib/wsgidav/samples
    copying wsgidav/samples/virtual_dav_provider.py -> build/lib/wsgidav/samples
    copying wsgidav/samples/__init__.py -> build/lib/wsgidav/samples
    copying wsgidav/samples/dav_provider_tools.py -> build/lib/wsgidav/samples
    copying wsgidav/samples/mongo_dav_provider.py -> build/lib/wsgidav/samples
    creating build/lib/wsgidav/server
    copying wsgidav/server/__init__.py -> build/lib/wsgidav/server
    copying wsgidav/server/run_server.py -> build/lib/wsgidav/server
    copying wsgidav/server/ext_wsgiutils_server.py -> build/lib/wsgidav/server
    copying wsgidav/server/run_reloading_server.py -> build/lib/wsgidav/server
    copying wsgidav/server/server_sample.py -> build/lib/wsgidav/server
    running build_exe
    creating directory build/exe.linux-x86_64-2.7
    copying /usr/local/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-linux-x86_64.egg/cx_Freeze/bases/Console -> build/exe.linux-x86_64-2.7/wsgidav.exe
    sh: /usr/bin/ldd: /usr/bin/bash: bad interpreter: No such file or directory
    copying doc/logo.ico -> build/exe.linux-x86_64-2.7/logo.ico
    error: [Errno 2] No such file or directory: 'doc/logo.ico'
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z2yvLQ/wsgidav/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MNXqFi-record/install-record.txt --compile" failed with error code 1 in /tmp/pip-build-z2yvLQ/wsgidav/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

my system infomation:
[root@localhost ~]# cat /etc/redhat-release 
CentOS release 6.7 (Final)
[root@localhost ~]# python -V
Python 2.7.8

**Comment by mar10** [comment]
Seems to be a known error message.
Maybe this helps:

 - add the --egg option: `pip install --egg wsgidav`
 - `pip install wheel`
 - update pip, or python to a newer version

http://stackoverflow.com/a/15258644/19166
