### ISSUE TITLE
Custom responses for PUTs etc.

### ISSUE THREAD

**Issue by samuelfekete** [mar10/wsgidav#55]
We need the ability to customise the response status and body for PUT requests (to support the s3 protocol on the client side).

We will probably also need this for GET and POST as mentioned [here](https://github.com/mar10/wsgidav/issues/48#issuecomment-253177004), so I think it would be good to think of a consistent way of doing this for all methods, and provide plugins with the ability to specify the status and body to return.

**Comment by mar10** [comment]
As discussed, a minimal invasive approach would be s.th. like
```py
    def doPUT(self, environ, start_response):
        ...
        res = provider.getResourceInst(path, environ)
        try:
            return res.handleRequestMethod(environ, start_response)
        except NotImplementedError:
            pass
```

with this default implementation
```py
    def handleRequestMethod(self, environ, responseHeaders):
        """Optionally implement custom request handling.

        requestmethod = environ["REQUEST_METHOD"]
        """
        raise NotImplementedError
```
This would allow for max. flexibility but require the custom handlers to re-implement a lot of request logic.
But note that res may be `None` for new files.

So a better idea might be to allow custom handling in the provider instead:

```py
class DAVProvider(object):
    def customRequestHandler(self, environ, start_response, defaultHandler):
        """Optionally implement custom request handling.

        requestmethod = environ["REQUEST_METHOD"]
        Either 
          - handle the request completely   
          - do additional processing and call defaultHandler(environ, start_response)
        """
        return defaultHandler(environ, start_response)
```

(Btw. [In general, WebDAV servers do not support POST](http://stackoverflow.com/a/22606899/19166))

**Comment by samuelfekete** [comment]
I agree that it makes more sense to override request methods in the provider rather than in the resource instance. Where would you call `customRequestHandler()`?

Another alternative we were considering is having the ability to raise a custom `DAVError`, which will give an alternative status code, headers, and body. This would solve most use cases where we do not need to change anything in the request method other than the return values (except for POST which will still need to be overridden). 

I'm aware that WebDav does not define POST, but it also doesn't ban it, and we have it as a requirement.

**Comment by samuelfekete** [comment]
I like the approach of `customRequestHandler` as it automatically solves the override problem for all request methods with one small change.
