### ISSUE TITLE
ETags for collections?

### ISSUE THREAD

**Issue by samuelfekete** [mar10/wsgidav#63]
I have implemented `get_Etag()` for a collection, but it never gets called. It appears that the directory browser ignores Etags. Is it possible to have Etags for collections?

**Comment by mar10** [comment]
Hi Samuel,

could explain how you calculate the etag and give some use cases, how clients would make use of this?

(If you are thinking about dir syncs, this may be interesting as well: https://tools.ietf.org/html/rfc6578 )

**Comment by samuelfekete** [comment]
@mar10, for now I was simply using the actual directory data. For expensive directory calls this could potentially be stored, for example, as a flag that gets removed when there's any change to the collection.

**Comment by mar10** [comment]
I would prefer to wait for some more up-votes, or concrete examples of other WebDAV clients/Servers that support this, Closing for now.
