### ISSUE TITLE
how to join into django

### ISSUE THREAD

**Issue by huarda** [mar10/wsgidav#68]
I create dajngo project .
how I can use wsgidav?

**Comment by mar10** [comment]
I have not used Django yet, so I don't know if you can mount a WSGI app inside your Django project.
But it seems that Django is a WSGI app itself, so it can be run inside a WSGI compliant server side by side with WsgiDAV. (The documentation mentions Apache mod_wsgi, ...: https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/)
I also can recommend CherryPy as a WSGI container.

**Comment by n3storm** [comment]
https://github.com/qdqmedia/django-templation

This django project uses wsgidav to allow django templates editing via webdav. Webdav users auth integration with Django auth.
