### ISSUE TITLE
Failed on processing non-iso-8859-1 characters on Python 3

### ISSUE THREAD

**Issue by yangfl** [mar10/wsgidav#73]
Hi,
I pulled the code directly from the repo, but when I tried to add `addShare("测试", r"~/")` into the config file, I encountered several problems.

* On Python 2:
`run_server.py` will immediately complain that
```
SyntaxError: Non-ASCII character '\xe6' in file /testdir/wsgidav.conf on line 107, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
This can be solved by adding
```
#encoding=utf8
```
at the very beginning of `wsgidav.conf`. After that, everything works fine.

* On Python 3:
The server will start normally, however, when typing
```
http://127.0.0.1:8080/%E6%B5%8B%E8%AF%95/
```
in the browser, the console will give
```
"GET /æµè¯/" elap=0.000sec -> 404 Not Found
```
and 404, which I cannot solve though :(

**Comment by mar10** [comment]
Reproduced with Python 3.4 on OS X

**Comment by luusl** [comment]
Any plans for a release of this fix?

**Comment by mar10** [comment]
Had some problems with the build and release framework - sorry for the delay.

**Comment by mar10** [comment]
WSGI always assumes iso-8859-1. Modern clients send UTF-8, so we may have to re-encode.

See also:
https://www.python.org/dev/peps/pep-3333/#unicode-issues
https://bugs.python.org/issue16679#msg177450

The current implementation does 

```py
if re_encode_path_info:
    environ["PATH_INFO"] = environ["PATH_INFO"].encode("iso-8859-1").decode("utf-8")
```
Where the `hotfixes.re_encode_path_info` option is true by default.
