### ISSUE TITLE
removeProperty called twice with dryRun=False

### ISSUE THREAD

**Issue by jbasko** [mar10/wsgidav#78]
In wsgidav/dav_provider.py line 761:
https://github.com/mar10/wsgidav/blob/master/wsgidav/dav_provider.py?utf8=%E2%9C%93#L761

`removeProperty` is not being passed `dryRun` argument which means that because `setPropertyValue` is called twice (once with `dryRun=True` and once with `dryRun=False`) it will be called twice with effectively `dryRun=False` which means a property will be deleted even if some other property update instruction fails so atomicity of PROPPATCH is broken.

The fix would be to just pass dryRun:

`return pm.removeProperty(refUrl, propname, dryRun)`

Pull request: https://github.com/mar10/wsgidav/pull/77

**Comment by mar10** [comment]
Thanks for contributing.

**Comment by jbasko** [comment]
Thanks for merging. Are you planning on doing a release any time soon?

**Comment by mar10** [comment]
Done.

**Comment by jbasko** [comment]
Thanks!
