### ISSUE TITLE
With COPY, source and destination must have the same scheme?

### ISSUE THREAD

**Issue by samuelfekete** [mar10/wsgidav#82]
When I try to do a COPY and the destination has a different scheme, I get this error:
`502 Bad Gateway: Source and destination must have the same scheme.`

Why do they have to have the same scheme?
Is there a way around this?

**Comment by samuelfekete** [comment]
I also need to be able to have different host names for the destination.

We are using COPY to export data to an external server.

**Comment by mar10** [comment]
AFAIK, WebDAV does not support copying files to another server, so I'd say the error is ok.
(If you want to copy between servers, you could send a GET to the source and then PUT/POST to the target?)
