### ISSUE TITLE
Facing Issue while logging into WebDAV using supervisor

### ISSUE THREAD

**Issue by vinay-is** [mar10/wsgidav#95]
We are using supervisor to launch our application which has WebDAV integration. 

The following code in wasgidav_app.py is failing as the value of 'sys.stdout.encoding' is coming as None when application is launched via supervisor. 

safeReEncode(environ.get("PATH_INFO", ""), sys.stdout.encoding)

I think instead of 'sys.stdout.encoding' we should function sys.getdefaultencoding()

**Comment by mar10** [comment]
@vinay-is did you check with v2.3.0?

**Comment by mar10** [comment]
Assuming fixed. Will re-open as needed.

**Comment by vinay-is** [comment]
Sorry did not got a chance to verify......will let you know if I face any
Issue......

**Comment by mar10** [comment]
no problem, thank you (btw., 2.4 is released now)
